using Last.Data.Master;
using Last.Interpreter;
using RomUtilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using UnityEngine.Bindings;
using UnityEngine;

namespace FF1PRAP
{
	public class Location
	{
		public string Name;
		public string Region;
		public LocationType Type;
		public int Flag;
		public List<AccessRequirements> BaseAccess;
		public List<List<AccessRequirements>> FullAccess;
		public AccessRequirements Trigger;
		public Location(string name, string region, LocationType type, int flag, List<AccessRequirements> access, AccessRequirements trigger = AccessRequirements.None)
		{
			Name = name;
			Region = region;
			Type = type;
			Flag = flag;
			BaseAccess = access;
			FullAccess = new();
			Trigger = trigger;
		}
		public Location(Location location, List<List<AccessRequirements>> allaccess)
		{ 
			Name = location.Name;
			Region = location.Region;
			Type = location.Type;
			Flag = location.Flag;
			BaseAccess = location.BaseAccess.ToList();
			Trigger = location.Trigger;

			FullAccess = new();

			foreach (var access in allaccess)
			{ 
				FullAccess.Add(access.Concat(BaseAccess).ToList());
			}
		}
	}

	partial class Logic
	{
		public static List<Location> FixedLocations = new()
		{
			new Location("Chaos Shrine - Unlocked Single", RegionNames.chaos_shrine, LocationType.Treasure, 5, new()),
			new Location("Chaos Shrine - Unlocked Duo 1", RegionNames.chaos_shrine, LocationType.Treasure, 6, new()),
			new Location("Chaos Shrine - Unlocked Duo 2", RegionNames.chaos_shrine, LocationType.Treasure, 7, new()),
			new Location("Chaos Shrine - Locked Single", RegionNames.chaos_shrine, LocationType.Treasure, 10, new() { AccessRequirements.MysticKey }),
			new Location("Chaos Shrine - Locked Duo 1", RegionNames.chaos_shrine, LocationType.Treasure, 8, new() { AccessRequirements.MysticKey }),
			new Location("Chaos Shrine - Locked Duo 2", RegionNames.chaos_shrine, LocationType.Treasure, 9, new() { AccessRequirements.MysticKey }),
			new Location("Castle Cornelia - Princess", RegionNames.castle_cornelia_2f, LocationType.GameObject, 400, new() { AccessRequirements.GarlandDefeated }),
			new Location("Castle Cornelia - Treasury 1", RegionNames.castle_cornelia_1f, LocationType.Treasure, 0, new() { AccessRequirements.MysticKey }),
			new Location("Castle Cornelia - Treasury 2", RegionNames.castle_cornelia_1f, LocationType.Treasure, 1, new() { AccessRequirements.MysticKey }),
			new Location("Castle Cornelia - Treasury 3", RegionNames.castle_cornelia_1f, LocationType.Treasure, 2, new() { AccessRequirements.MysticKey }),
			new Location("Castle Cornelia - Treasury 4", RegionNames.castle_cornelia_1f, LocationType.Treasure, 3, new() { AccessRequirements.MysticKey }),
			new Location("Castle Cornelia - Treasury 5", RegionNames.castle_cornelia_1f, LocationType.Treasure, 4, new() { AccessRequirements.MysticKey }),
			new Location("Castle Cornelia - Treasury Major", RegionNames.castle_cornelia_1f, LocationType.Treasure, 505, new() { AccessRequirements.MysticKey }),
			new Location("Matoya's Cave - Chest 1", RegionNames.matoyas_cave, LocationType.Treasure, 11, new()),
			new Location("Matoya's Cave - Chest 2", RegionNames.matoyas_cave, LocationType.Treasure, 12, new()),
			new Location("Matoya's Cave - Chest 3", RegionNames.matoyas_cave, LocationType.Treasure, 13, new()),
			new Location("Matoya's Cave - Matoya", RegionNames.matoyas_cave, LocationType.GameObject, 247, new() { AccessRequirements.CrystalEye }),
			new Location("Pravoka - Bikke", RegionNames.pravoka, LocationType.GameObject, 401, new()),
			new Location("Marsh Cave B2 (Top) - Single", RegionNames.marsh_cave_b2_top, LocationType.Treasure, 24, new()),
			new Location("Marsh Cave B2 (Top) - Corner", RegionNames.marsh_cave_b2_top, LocationType.Treasure, 232, new()),
			new Location("Marsh Cave B2 (Top) - Duo 1", RegionNames.marsh_cave_b2_top, LocationType.Treasure, 21, new()),
			new Location("Marsh Cave B2 (Top) - Duo 2", RegionNames.marsh_cave_b2_top, LocationType.Treasure, 22, new()),
			new Location("Marsh Cave B2 (Bottom) - Leftmost Chest", RegionNames.marsh_cave_b2_bottom, LocationType.Treasure, 231, new()),
			new Location("Marsh Cave B2 (Bottom) - Center Chest", RegionNames.marsh_cave_b2_bottom, LocationType.Treasure, 23, new()),
			new Location("Marsh Cave B2 (Bottom) - Rightmost Chest", RegionNames.marsh_cave_b2_bottom, LocationType.Treasure, 233, new()),
			new Location("Marsh Cave B3 (Bottom) - Distant Chest", RegionNames.marsh_cave_b3, LocationType.Treasure, 25, new()),
			new Location("Marsh Cave B3 (Bottom) - Tetris-Z First", RegionNames.marsh_cave_b3, LocationType.Treasure, 26, new()),
			new Location("Marsh Cave B3 (Bottom) - Tetris-Z Middle 1", RegionNames.marsh_cave_b3, LocationType.Treasure, 27, new()),
			new Location("Marsh Cave B3 (Bottom) - Tetris-Z Middle 2", RegionNames.marsh_cave_b3, LocationType.Treasure, 234, new()),
			new Location("Marsh Cave B3 (Bottom) - Tetris-Z Major", RegionNames.marsh_cave_b3, LocationType.Treasure, 501, new()),
			new Location("Marsh Cave B3 (Bottom) - Tetris-Z Last", RegionNames.marsh_cave_b3, LocationType.Treasure, 28, new()),
			new Location("Marsh Cave B3 (Bottom) - First Room Chest", RegionNames.marsh_cave_b3, LocationType.Treasure, 29, new()),
			new Location("Marsh Cave B3 (Bottom) - Dunno Chest", RegionNames.marsh_cave_b3, LocationType.Treasure, 235, new()),
			new Location("Marsh Cave B3 (Bottom) - Locked Corner", RegionNames.marsh_cave_b3, LocationType.Treasure, 30, new() { AccessRequirements.MysticKey }),
			new Location("Marsh Cave B3 (Bottom) - Locked Middle", RegionNames.marsh_cave_b3, LocationType.Treasure, 31, new() { AccessRequirements.MysticKey }),
			new Location("Marsh Cave B3 (Bottom) - Locked Cross", RegionNames.marsh_cave_b3, LocationType.Treasure, 32, new() { AccessRequirements.MysticKey }),
			new Location("Western Keep - Astos", RegionNames.western_keep, LocationType.GameObject, 246, new() { AccessRequirements.Crown }),
			new Location("Western Keep - Treasury 1", RegionNames.western_keep, LocationType.Treasure, 18, new() { AccessRequirements.MysticKey }),
			new Location("Western Keep - Treasury 2", RegionNames.western_keep, LocationType.Treasure, 19, new() { AccessRequirements.MysticKey }),
			new Location("Western Keep - Treasury 3", RegionNames.western_keep, LocationType.Treasure, 20, new() { AccessRequirements.MysticKey }),
			new Location("Elven Castle - Elf Prince", RegionNames.elven_castle, LocationType.GameObject, 248, new() { AccessRequirements.JoltTonic }),
			new Location("Elven Castle - Treasury 1", RegionNames.elven_castle, LocationType.Treasure, 14, new() { AccessRequirements.MysticKey }),
			new Location("Elven Castle - Treasury 2", RegionNames.elven_castle, LocationType.Treasure, 15, new() { AccessRequirements.MysticKey }),
			new Location("Elven Castle - Treasury 3", RegionNames.elven_castle, LocationType.Treasure, 16, new() { AccessRequirements.MysticKey }),
			new Location("Elven Castle - Treasury 4", RegionNames.elven_castle, LocationType.Treasure, 17, new() { AccessRequirements.MysticKey }),
			new Location("Mount Duergar - Entrance 1", RegionNames.mount_duergar, LocationType.Treasure, 33, new()),
			new Location("Mount Duergar - Entrance 2", RegionNames.mount_duergar, LocationType.Treasure, 34, new()),
			new Location("Mount Duergar - Treasury 1", RegionNames.mount_duergar, LocationType.Treasure, 35, new() { AccessRequirements.MysticKey }),
			new Location("Mount Duergar - Treasury 2", RegionNames.mount_duergar, LocationType.Treasure, 36, new() { AccessRequirements.MysticKey }),
			new Location("Mount Duergar - Treasury 3", RegionNames.mount_duergar, LocationType.Treasure, 37, new() { AccessRequirements.MysticKey }),
			new Location("Mount Duergar - Treasury 4", RegionNames.mount_duergar, LocationType.Treasure, 38, new() { AccessRequirements.MysticKey }),
			new Location("Mount Duergar - Treasury 5", RegionNames.mount_duergar, LocationType.Treasure, 39, new() { AccessRequirements.MysticKey }),
			new Location("Mount Duergar - Treasury 6", RegionNames.mount_duergar, LocationType.Treasure, 40, new() { AccessRequirements.MysticKey }),
			new Location("Mount Duergar - Treasury 7", RegionNames.mount_duergar, LocationType.Treasure, 41, new() { AccessRequirements.MysticKey }),
			new Location("Mount Duergar - Treasury 8", RegionNames.mount_duergar, LocationType.Treasure, 42, new() { AccessRequirements.MysticKey }),
			new Location("Mount Duergar - Smitt", RegionNames.mount_duergar, LocationType.GameObject, 405, new() { AccessRequirements.Adamantite }),
			new Location("Cavern of Earth B1 - Single", RegionNames.cavern_of_earth_b1, LocationType.Treasure, 43, new()),
			new Location("Cavern of Earth B1 - Appendix 1", RegionNames.cavern_of_earth_b1, LocationType.Treasure, 44, new()),
			new Location("Cavern of Earth B1 - Appendix 2", RegionNames.cavern_of_earth_b1, LocationType.Treasure, 45, new()),
			new Location("Cavern of Earth B1 - Side Path 1", RegionNames.cavern_of_earth_b1, LocationType.Treasure, 46, new()),
			new Location("Cavern of Earth B1 - Side Path 2", RegionNames.cavern_of_earth_b1, LocationType.Treasure, 47, new()),
			new Location("Cavern of Earth B2 - Guarded 1", RegionNames.cavern_of_earth_b2, LocationType.Treasure, 48, new()),
			new Location("Cavern of Earth B2 - Guarded 2", RegionNames.cavern_of_earth_b2, LocationType.Treasure, 49, new()),
			new Location("Cavern of Earth B2 - Guarded 3", RegionNames.cavern_of_earth_b2, LocationType.Treasure, 50, new()),
			new Location("Cavern of Earth B2 - Side Room 1", RegionNames.cavern_of_earth_b2, LocationType.Treasure, 51, new()),
			new Location("Cavern of Earth B2 - Side Room 2", RegionNames.cavern_of_earth_b2, LocationType.Treasure, 52, new()),
			new Location("Cavern of Earth B2 - Side Room 3", RegionNames.cavern_of_earth_b2, LocationType.Treasure, 53, new()),
			new Location("Cavern of Earth B3 - Side Room", RegionNames.cavern_of_earth_b3, LocationType.Treasure, 54, new()),
			new Location("Cavern of Earth B3 - TFC", RegionNames.cavern_of_earth_b3, LocationType.Treasure, 55, new()),
			new Location("Cavern of Earth B3 - Asher Trunk", RegionNames.cavern_of_earth_b3, LocationType.Treasure, 56, new()),
			new Location("Cavern of Earth B3 - Vampire's Closet", RegionNames.cavern_of_earth_b3, LocationType.Treasure, 57, new()),
			new Location("Cavern of Earth B3 - Vampire's Chest", RegionNames.cavern_of_earth_b3, LocationType.Treasure, 508, new()),
			new Location("Cavern of Earth B4 - Armory 1", RegionNames.cavern_of_earth_b4, LocationType.Treasure, 58, new()),
			new Location("Cavern of Earth B4 - Armory 2", RegionNames.cavern_of_earth_b4, LocationType.Treasure, 59, new()),
			new Location("Cavern of Earth B4 - Armory 3", RegionNames.cavern_of_earth_b4, LocationType.Treasure, 60, new()),
			new Location("Cavern of Earth B4 - Armory 4", RegionNames.cavern_of_earth_b4, LocationType.Treasure, 61, new()),
			new Location("Cavern of Earth B4 - Armory 5", RegionNames.cavern_of_earth_b4, LocationType.Treasure, 62, new()),
			new Location("Cavern of Earth B4 - Lich's Closet 1", RegionNames.cavern_of_earth_b4, LocationType.Treasure, 63, new()),
			new Location("Cavern of Earth B4 - Lich's Closet 2", RegionNames.cavern_of_earth_b4, LocationType.Treasure, 64, new()),
			new Location("Cavern of Earth B4 - Lich's Closet 3", RegionNames.cavern_of_earth_b4, LocationType.Treasure, 65, new()),
			new Location("Giant's Cave - Chest 1", RegionNames.giants_cavern, LocationType.Treasure, 241, new() { AccessRequirements.TitanFed }),
			new Location("Giant's Cave - Chest 2", RegionNames.giants_cavern, LocationType.Treasure, 242, new() { AccessRequirements.TitanFed }),
			new Location("Giant's Cave - Chest 3", RegionNames.giants_cavern, LocationType.Treasure, 243, new() { AccessRequirements.TitanFed }),
			new Location("Giant's Cave - Chest 4", RegionNames.giants_cavern, LocationType.Treasure, 244, new() { AccessRequirements.TitanFed }),
			new Location("Sage's Cave - Sarda", RegionNames.sages_cave, LocationType.GameObject, 253, new() { AccessRequirements.VampireDefeated }),
			new Location("Crescent Lake - Canoe Sage", RegionNames.crescent_lake, LocationType.GameObject, 402, new() { AccessRequirements.EarthCrystal }),
			new Location("Mount Gulg B2 - Guarded", RegionNames.mount_gulg_b2, LocationType.Treasure, 66, new()),
			new Location("Mount Gulg B2 - Center", RegionNames.mount_gulg_b2, LocationType.Treasure, 67, new()),
			new Location("Mount Gulg B2 - Hairpins", RegionNames.mount_gulg_b2, LocationType.Treasure, 68, new()),
			new Location("Mount Gulg B2 - Shortpins", RegionNames.mount_gulg_b2, LocationType.Treasure, 69, new()),
			new Location("Mount Gulg B2 - Vertpins 1", RegionNames.mount_gulg_b2, LocationType.Treasure, 70, new()),
			new Location("Mount Gulg B2 - Vertpins 2", RegionNames.mount_gulg_b2, LocationType.Treasure, 71, new()),
			new Location("Mount Gulg B2 - Armory 1", RegionNames.mount_gulg_b2, LocationType.Treasure, 72, new()),
			new Location("Mount Gulg B2 - Armory 2", RegionNames.mount_gulg_b2, LocationType.Treasure, 73, new()),
			new Location("Mount Gulg B2 - Armory 3", RegionNames.mount_gulg_b2, LocationType.Treasure, 74, new()),
			new Location("Mount Gulg B2 - Armory 4", RegionNames.mount_gulg_b2, LocationType.Treasure, 75, new()),
			new Location("Mount Gulg B2 - Armory 5", RegionNames.mount_gulg_b2, LocationType.Treasure, 76, new()),
			new Location("Mount Gulg B2 - Armory 6", RegionNames.mount_gulg_b2, LocationType.Treasure, 77, new()),
			new Location("Mount Gulg B2 - Armory 7", RegionNames.mount_gulg_b2, LocationType.Treasure, 78, new()),
			new Location("Mount Gulg B2 - Armory 8", RegionNames.mount_gulg_b2, LocationType.Treasure, 79, new()),
			new Location("Mount Gulg B2 - Armory 9", RegionNames.mount_gulg_b2, LocationType.Treasure, 80, new()),
			new Location("Mount Gulg B2 - Armory 10", RegionNames.mount_gulg_b2, LocationType.Treasure, 81, new()),
			new Location("Mount Gulg B2 - Armory 11", RegionNames.mount_gulg_b2, LocationType.Treasure, 82, new()),
			new Location("Mount Gulg B2 - Armory 12", RegionNames.mount_gulg_b2, LocationType.Treasure, 83, new()),
			new Location("Mount Gulg B4 - Entrance 1", RegionNames.mount_gulg_b4_agama, LocationType.Treasure, 84, new()),
			new Location("Mount Gulg B4 - Entrance 2", RegionNames.mount_gulg_b4_agama, LocationType.Treasure, 85, new()),
			new Location("Mount Gulg B4 - First Greed", RegionNames.mount_gulg_b4_agama, LocationType.Treasure, 86, new()),
			new Location("Mount Gulg B4 - Worm Room 1", RegionNames.mount_gulg_b4_agama, LocationType.Treasure, 87, new()),
			new Location("Mount Gulg B4 - Worm Room 2", RegionNames.mount_gulg_b4_agama, LocationType.Treasure, 88, new()),
			new Location("Mount Gulg B4 - Worm Room 3", RegionNames.mount_gulg_b4_agama, LocationType.Treasure, 89, new()),
			new Location("Mount Gulg B4 - Worm Room 4", RegionNames.mount_gulg_b4_agama, LocationType.Treasure, 90, new()),
			new Location("Mount Gulg B4 - Worm Room 5", RegionNames.mount_gulg_b4_agama, LocationType.Treasure, 91, new()),
			new Location("Mount Gulg B4 - Second Greed 1", RegionNames.mount_gulg_b4_agama, LocationType.Treasure, 92, new()),
			new Location("Mount Gulg B4 - Second Greed 2", RegionNames.mount_gulg_b4_agama, LocationType.Treasure, 93, new()),
			new Location("Mount Gulg B4 - Side Room 1", RegionNames.mount_gulg_b4_agama, LocationType.Treasure, 94, new()),
			new Location("Mount Gulg B4 - Side Room 2", RegionNames.mount_gulg_b4_agama, LocationType.Treasure, 95, new()),
			new Location("Mount Gulg B4 - Side Room 3", RegionNames.mount_gulg_b4_agama, LocationType.Treasure, 236, new()),
			new Location("Mount Gulg B4 - Last Room 1", RegionNames.mount_gulg_b4_agama, LocationType.Treasure, 96, new()),
			new Location("Mount Gulg B4 - Last Room 2", RegionNames.mount_gulg_b4_agama, LocationType.Treasure, 97, new()),
			new Location("Mount Gulg B5 - West Room", RegionNames.mount_gulg_b5, LocationType.Treasure, 98, new()),
			new Location("Mount Gulg B5 - Northeast Room", RegionNames.mount_gulg_b5, LocationType.Treasure, 237, new()),
			new Location("Mount Gulg B5 - East Room", RegionNames.mount_gulg_b5, LocationType.Treasure, 238, new()),
			new Location("Mount Gulg B5 - Southeast Room", RegionNames.mount_gulg_b5, LocationType.Treasure, 239, new()),
			new Location("Cavern of Ice B2 - Chest 1", RegionNames.cavern_of_ice_b2_room, LocationType.Treasure, 104, new()),
			new Location("Cavern of Ice B2 - Chest 2", RegionNames.cavern_of_ice_b2_room, LocationType.Treasure, 105, new()),
			new Location("Cavern of Ice B2 - Eye's Treasure", RegionNames.cavern_of_ice_b2_ledge, LocationType.GameObject, 254, new()),
			new Location("Cavern of Ice B3 - Ice Dragon Room 1", RegionNames.cavern_of_ice_b3_treasury, LocationType.Treasure, 106, new()),
			new Location("Cavern of Ice B3 - Ice Dragon Room 2", RegionNames.cavern_of_ice_b3_treasury, LocationType.Treasure, 107, new()),
			new Location("Cavern of Ice B3 - Six-Pack 1", RegionNames.cavern_of_ice_b3_treasury, LocationType.Treasure, 108, new()),
			new Location("Cavern of Ice B3 - Six-Pack 2", RegionNames.cavern_of_ice_b3_treasury, LocationType.Treasure, 109, new()),
			new Location("Cavern of Ice B3 - Six-Pack 3", RegionNames.cavern_of_ice_b3_treasury, LocationType.Treasure, 110, new()),
			new Location("Cavern of Ice B3 - Six-Pack 4", RegionNames.cavern_of_ice_b3_treasury, LocationType.Treasure, 111, new()),
			new Location("Cavern of Ice B3 - Six-Pack 5", RegionNames.cavern_of_ice_b3_treasury, LocationType.Treasure, 112, new()),
			new Location("Cavern of Ice B3 - Six-Pack 6", RegionNames.cavern_of_ice_b3_treasury, LocationType.Treasure, 113, new()),
			new Location("Cavern of Ice B1 - Greed 1", RegionNames.cavern_of_ice_b1_backdoor, LocationType.Treasure, 99, new()),
			new Location("Cavern of Ice B1 - Greed 2", RegionNames.cavern_of_ice_b1_backdoor, LocationType.Treasure, 100, new()),
			new Location("Cavern of Ice B1 - Drop Room 1", RegionNames.cavern_of_ice_b1_backdoor, LocationType.Treasure, 101, new()),
			new Location("Cavern of Ice B1 - Drop Room 2", RegionNames.cavern_of_ice_b1_backdoor, LocationType.Treasure, 102, new()),
			new Location("Cavern of Ice B1 - Drop Room 3", RegionNames.cavern_of_ice_b1_backdoor, LocationType.Treasure, 103, new()),
			new Location("Citadel of Trials 2F - Side Chest", RegionNames.citadel_of_trials_2f, LocationType.Treasure, 240, new()),
			new Location("Citadel of Trials 3F - Single", RegionNames.citadel_of_trials_2f, LocationType.Treasure, 210, new()),
			new Location("Citadel of Trials 3F - Three-Pack 1", RegionNames.citadel_of_trials_2f, LocationType.Treasure, 211, new()),
			new Location("Citadel of Trials 3F - Three-Pack 2", RegionNames.citadel_of_trials_2f, LocationType.Treasure, 212, new()),
			new Location("Citadel of Trials 3F - Three-Pack 3", RegionNames.citadel_of_trials_2f, LocationType.Treasure, 213, new()),
			new Location("Citadel of Trials 3F - Four-Pack 1", RegionNames.citadel_of_trials_2f, LocationType.Treasure, 214, new()),
			new Location("Citadel of Trials 3F - Four-Pack 2", RegionNames.citadel_of_trials_2f, LocationType.Treasure, 215, new()),
			new Location("Citadel of Trials 3F - Four-Pack 3", RegionNames.citadel_of_trials_2f, LocationType.Treasure, 216, new()),
			new Location("Citadel of Trials 3F - Four-Pack 4", RegionNames.citadel_of_trials_2f, LocationType.Treasure, 217, new()),
			new Location("Citadel of Trials 3F - Mouse Chest", RegionNames.citadel_of_trials_2f, LocationType.Treasure, 512, new()),
			new Location("Dragon Caves (Forest) - Entrance 1", RegionNames.dragon_caves_forest, LocationType.Treasure, 224, new()),
			new Location("Dragon Caves (Forest) - Entrance 2", RegionNames.dragon_caves_forest, LocationType.Treasure, 225, new()),
			new Location("Dragon Caves (Forest) - Entrance 3", RegionNames.dragon_caves_forest, LocationType.Treasure, 226, new()),
			new Location("Dragon Caves (Forest) - West Room 1", RegionNames.dragon_caves_forest, LocationType.Treasure, 227, new()),
			new Location("Dragon Caves (Forest) - West Room 2", RegionNames.dragon_caves_forest, LocationType.Treasure, 228, new()),
			new Location("Dragon Caves (Forest) - West Room 3", RegionNames.dragon_caves_forest, LocationType.Treasure, 229, new()),
			new Location("Dragon Caves (Forest) - West Room 4", RegionNames.dragon_caves_forest, LocationType.Treasure, 230, new()),
			new Location("Dragon Caves (Marsh) - Chest 1", RegionNames.dragon_caves_marsh, LocationType.Treasure, 221, new()),
			new Location("Dragon Caves (Marsh) - Chest 2", RegionNames.dragon_caves_marsh, LocationType.Treasure, 222, new()),
			new Location("Dragon Caves (Marsh) - Chest 3", RegionNames.dragon_caves_marsh, LocationType.Treasure, 223, new()),
			new Location("Dragon Caves (Plains) - Entrance", RegionNames.dragon_caves_plains, LocationType.Treasure, 218, new()),
			new Location("Dragon Caves (Plains) - Duo 1", RegionNames.dragon_caves_plains, LocationType.Treasure, 219, new()),
			new Location("Dragon Caves (Plains) - Duooo 2", RegionNames.dragon_caves_plains, LocationType.Treasure, 220, new()),
			new Location("Dragon Caves - Bahamut", RegionNames.dragon_caves_bahamut_hall, LocationType.GameObject, 407, new() { AccessRequirements.RatsTail }),
			new Location("Onrac Desert - Caravan", RegionNames.caravan_tent, LocationType.GameObject, 406, new()),
			new Location("Waterfall Caverns - Chest 1", RegionNames.waterfall, LocationType.Treasure, 114, new()),
			new Location("Waterfall Caverns - Chest 2", RegionNames.waterfall, LocationType.Treasure, 115, new()),
			new Location("Waterfall Caverns - Chest 3", RegionNames.waterfall, LocationType.Treasure, 116, new()),
			new Location("Waterfall Caverns - Chest 4", RegionNames.waterfall, LocationType.Treasure, 117, new()),
			new Location("Waterfall Caverns - Chest 5", RegionNames.waterfall, LocationType.Treasure, 118, new()),
			new Location("Waterfall Caverns - Chest 6", RegionNames.waterfall, LocationType.Treasure, 119, new()),
			new Location("Waterfall Caverns - CubeBot", RegionNames.waterfall, LocationType.GameObject, 404, new()),
			new Location("Gaia - Fairy", RegionNames.gaia, LocationType.GameObject, 403, new() { AccessRequirements.BottledFaerie }),
			new Location("Sunken Shrine 3F (Split) - Kraken Side Chest", RegionNames.sunken_shrine_3f_split, LocationType.Treasure, 130, new()),
			new Location("Sunken Shrine 3F (Split) - Mermaids Side Chest", RegionNames.sunken_shrine_3f_split, LocationType.Treasure, 131, new()),
			new Location("Sunken Shrine 4F (TFC) - TFC", RegionNames.sunken_shrine_4f_tfc, LocationType.Treasure, 134, new()),
			new Location("Sunken Shrine 4F (TFC) - TFC North", RegionNames.sunken_shrine_4f_tfc, LocationType.Treasure, 135, new()),
			new Location("Sunken Shrine 4F (TFC) - Side Corner", RegionNames.sunken_shrine_4f_tfc, LocationType.Treasure, 136, new()),
			new Location("Sunken Shrine 4F (TFC) - First Greed", RegionNames.sunken_shrine_4f_tfc, LocationType.Treasure, 137, new()),
			new Location("Sunken Shrine 4F (TFC) - Second Greed", RegionNames.sunken_shrine_4f_tfc, LocationType.Treasure, 138, new()),
			new Location("Sunken Shrine 5F - Passby", RegionNames.sunken_shrine_5f, LocationType.Treasure, 139, new()),
			new Location("Sunken Shrine 5F - Bubbles 1", RegionNames.sunken_shrine_5f, LocationType.Treasure, 140, new()),
			new Location("Sunken Shrine 5F - Bubbles 2", RegionNames.sunken_shrine_5f, LocationType.Treasure, 141, new()),
			new Location("Sunken Shrine 5F - Far Room 1", RegionNames.sunken_shrine_5f, LocationType.Treasure, 142, new()),
			new Location("Sunken Shrine 5F - Far Room 2", RegionNames.sunken_shrine_5f, LocationType.Treasure, 143, new()),
			new Location("Sunken Shrine 5F - Far Major", RegionNames.sunken_shrine_5f, LocationType.Treasure, 507, new()),
			new Location("Sunken Shrine 5F - Entrance 1", RegionNames.sunken_shrine_5f, LocationType.Treasure, 144, new()),
			new Location("Sunken Shrine 5F - Entrance 2", RegionNames.sunken_shrine_5f, LocationType.Treasure, 145, new()),
			new Location("Sunken Shrine 5F - Entrance 3", RegionNames.sunken_shrine_5f, LocationType.Treasure, 146, new()),
			new Location("Sunken Shrine 5F - Four-Corner 1", RegionNames.sunken_shrine_5f, LocationType.Treasure, 147, new()),
			new Location("Sunken Shrine 5F - Four-Corner 2", RegionNames.sunken_shrine_5f, LocationType.Treasure, 148, new()),
			new Location("Sunken Shrine 5F - Four-Corner 3", RegionNames.sunken_shrine_5f, LocationType.Treasure, 149, new()),
			new Location("Sunken Shrine 5F - Four-Corner 4", RegionNames.sunken_shrine_5f, LocationType.Treasure, 150, new()),
			new Location("Sunken Shrine 3F (Vertical) - Top Chest", RegionNames.sunken_shrine_3f_vertical, LocationType.Treasure, 132, new()),
			new Location("Sunken Shrine 3F (Vertical) - Bottom Chest", RegionNames.sunken_shrine_3f_vertical, LocationType.Treasure, 133, new()),
			new Location("Sunken Shrine 2F (Sharknado) - Dengbait 1", RegionNames.sunken_shrine_2f_sharknado, LocationType.Treasure, 120, new()),
			new Location("Sunken Shrine 2F (Sharknado) - Dengbait 2", RegionNames.sunken_shrine_2f_sharknado, LocationType.Treasure, 121, new()),
			new Location("Sunken Shrine 2F (Sharknado) - Side Corner 1", RegionNames.sunken_shrine_2f_sharknado, LocationType.Treasure, 122, new()),
			new Location("Sunken Shrine 2F (Sharknado) - Side Corner 2", RegionNames.sunken_shrine_2f_sharknado, LocationType.Treasure, 123, new()),
			new Location("Sunken Shrine 2F (Sharknado) - Side Corner 3", RegionNames.sunken_shrine_2f_sharknado, LocationType.Treasure, 124, new()),
			new Location("Sunken Shrine 2F (Sharknado) - Exit", RegionNames.sunken_shrine_2f_sharknado, LocationType.Treasure, 125, new()),
			new Location("Sunken Shrine 2F (Sharknado) - Shark 1", RegionNames.sunken_shrine_2f_sharknado, LocationType.Treasure, 126, new()),
			new Location("Sunken Shrine 2F (Sharknado) - Shark 2", RegionNames.sunken_shrine_2f_sharknado, LocationType.Treasure, 127, new()),
			new Location("Sunken Shrine 2F (Sharknado) - Shark 3", RegionNames.sunken_shrine_2f_sharknado, LocationType.Treasure, 128, new()),
			new Location("Sunken Shrine 2F (Sharknado) - Shark 4", RegionNames.sunken_shrine_2f_sharknado, LocationType.Treasure, 129, new()),
			new Location("Lufenia - Lufenian Man", RegionNames.lufenia, LocationType.GameObject, 255, new() { AccessRequirements.TranslatedRosettaStone }),
			new Location("Mirage Tower 1F - Chest 1", RegionNames.mirage_tower_1f, LocationType.Treasure, 151, new()),
			new Location("Mirage Tower 1F - Chest 2", RegionNames.mirage_tower_1f, LocationType.Treasure, 152, new()),
			new Location("Mirage Tower 1F - Chest 3", RegionNames.mirage_tower_1f, LocationType.Treasure, 153, new()),
			new Location("Mirage Tower 1F - Chest 4", RegionNames.mirage_tower_1f, LocationType.Treasure, 154, new()),
			new Location("Mirage Tower 1F - Chest 5", RegionNames.mirage_tower_1f, LocationType.Treasure, 155, new()),
			new Location("Mirage Tower 1F - Chest 6", RegionNames.mirage_tower_1f, LocationType.Treasure, 156, new()),
			new Location("Mirage Tower 1F - Chest 7", RegionNames.mirage_tower_1f, LocationType.Treasure, 157, new()),
			new Location("Mirage Tower 1F - Chest 8", RegionNames.mirage_tower_1f, LocationType.Treasure, 158, new()),
			new Location("Mirage Tower 2F - Lesser 1", RegionNames.mirage_tower_2f, LocationType.Treasure, 159, new()),
			new Location("Mirage Tower 2F - Lesser 2", RegionNames.mirage_tower_2f, LocationType.Treasure, 160, new()),
			new Location("Mirage Tower 2F - Lesser 3", RegionNames.mirage_tower_2f, LocationType.Treasure, 161, new()),
			new Location("Mirage Tower 2F - Lesser 4", RegionNames.mirage_tower_2f, LocationType.Treasure, 162, new()),
			new Location("Mirage Tower 2F - Lesser 5", RegionNames.mirage_tower_2f, LocationType.Treasure, 163, new()),
			new Location("Mirage Tower 2F - Greater 1", RegionNames.mirage_tower_2f, LocationType.Treasure, 164, new()),
			new Location("Mirage Tower 2F - Greater 2", RegionNames.mirage_tower_2f, LocationType.Treasure, 165, new()),
			new Location("Mirage Tower 2F - Greater 3", RegionNames.mirage_tower_2f, LocationType.Treasure, 166, new()),
			new Location("Mirage Tower 2F - Greater 4", RegionNames.mirage_tower_2f, LocationType.Treasure, 167, new()),
			new Location("Mirage Tower 2F - Greater 5", RegionNames.mirage_tower_2f, LocationType.Treasure, 168, new()),
			new Location("Flying Fortress 1F - Solo", RegionNames.flying_fortress_1f, LocationType.Treasure, 178, new()),
			new Location("Flying Fortress 1F - West Room 1", RegionNames.flying_fortress_1f, LocationType.Treasure, 169, new()),
			new Location("Flying Fortress 1F - West Room 2", RegionNames.flying_fortress_1f, LocationType.Treasure, 170, new()),
			new Location("Flying Fortress 1F - West Room 3", RegionNames.flying_fortress_1f, LocationType.Treasure, 171, new()),
			new Location("Flying Fortress 1F - West Room 4", RegionNames.flying_fortress_1f, LocationType.Treasure, 172, new()),
			new Location("Flying Fortress 1F - East Room 1", RegionNames.flying_fortress_1f, LocationType.Treasure, 173, new()),
			new Location("Flying Fortress 1F - East Room 2", RegionNames.flying_fortress_1f, LocationType.Treasure, 174, new()),
			new Location("Flying Fortress 1F - East Room 3", RegionNames.flying_fortress_1f, LocationType.Treasure, 175, new()),
			new Location("Flying Fortress 1F - East Room 4", RegionNames.flying_fortress_1f, LocationType.Treasure, 176, new()),
			new Location("Flying Fortress 1F - East Room 5", RegionNames.flying_fortress_1f, LocationType.Treasure, 177, new()),
			new Location("Flying Fortress 2F - Cheap Room 1", RegionNames.flying_fortress_2f, LocationType.Treasure, 179, new()),
			new Location("Flying Fortress 2F - Cheap Room 2", RegionNames.flying_fortress_2f, LocationType.Treasure, 180, new()),
			new Location("Flying Fortress 2F - Vault 1", RegionNames.flying_fortress_2f, LocationType.Treasure, 181, new()),
			new Location("Flying Fortress 2F - Vault 2", RegionNames.flying_fortress_2f, LocationType.Treasure, 182, new()),
			new Location("Flying Fortress 2F - Major", RegionNames.flying_fortress_2f, LocationType.Treasure, 250, new()),
			new Location("Flying Fortress 2F - Gauntlet Room", RegionNames.flying_fortress_2f, LocationType.Treasure, 183, new()),
			new Location("Flying Fortress 2F - Ribbon Room 1", RegionNames.flying_fortress_2f, LocationType.Treasure, 184, new()),
			new Location("Flying Fortress 2F - Ribbon Room 2", RegionNames.flying_fortress_2f, LocationType.Treasure, 185, new()),
			new Location("Flying Fortress 2F - Wardrobe 1", RegionNames.flying_fortress_2f, LocationType.Treasure, 186, new()),
			new Location("Flying Fortress 2F - Wardrobe 2", RegionNames.flying_fortress_2f, LocationType.Treasure, 187, new()),
			new Location("Flying Fortress 3F - CC's Gambit 1", RegionNames.flying_fortress_3f, LocationType.Treasure, 188, new()),
			new Location("Flying Fortress 3F - CC's Gambit 2", RegionNames.flying_fortress_3f, LocationType.Treasure, 189, new()),
			new Location("Flying Fortress 3F - CC's Gambit 3", RegionNames.flying_fortress_3f, LocationType.Treasure, 190, new()),
			new Location("Flying Fortress 3F - CC's Gambit 4", RegionNames.flying_fortress_3f, LocationType.Treasure, 191, new()),
			new Location("Flying Fortress 3F - Six-Pack 1", RegionNames.flying_fortress_3f, LocationType.Treasure, 192, new()),
			new Location("Flying Fortress 3F - Six-Pack 2", RegionNames.flying_fortress_3f, LocationType.Treasure, 193, new()),
			new Location("Flying Fortress 3F - Six-Pack 3", RegionNames.flying_fortress_3f, LocationType.Treasure, 194, new()),
			new Location("Flying Fortress 3F - Six-Pack 4", RegionNames.flying_fortress_3f, LocationType.Treasure, 195, new()),
			new Location("Flying Fortress 3F - Six-Pack 5", RegionNames.flying_fortress_3f, LocationType.Treasure, 196, new()),
			new Location("Flying Fortress 3F - Six-Pack 6", RegionNames.flying_fortress_3f, LocationType.Treasure, 197, new()),
			new Location("Flying Fortress 3F - Exit 1", RegionNames.flying_fortress_3f, LocationType.Treasure, 198, new()),
			new Location("Flying Fortress 3F - Exit 2", RegionNames.flying_fortress_3f, LocationType.Treasure, 199, new()),
			new Location("Flying Fortress 3F - Exit 3", RegionNames.flying_fortress_3f, LocationType.Treasure, 200, new()),
			new Location("Flying Fortress 3F - Exit 4", RegionNames.flying_fortress_3f, LocationType.Treasure, 201, new()),
			new Location("Chaos Shrine 3F - Validation 1", RegionNames.chaos_shrine_3f_plaza, LocationType.Treasure, 202, new()),
			new Location("Chaos Shrine 3F - Validation 2", RegionNames.chaos_shrine_3f_plaza, LocationType.Treasure, 203, new()),
			new Location("Chaos Shrine B2 (Fire) - Right Chest", RegionNames.chaos_shrine_b2, LocationType.Treasure, 204, new()),
			new Location("Chaos Shrine B2 (Fire) - Left Chest", RegionNames.chaos_shrine_b2, LocationType.Treasure, 205, new()),
			new Location("Chaos Shrine B2 (Fire) - Eastern Vault", RegionNames.chaos_shrine_b2, LocationType.Treasure, 206, new()),
			new Location("Chaos Shrine B2 (Fire) - Southern Vault", RegionNames.chaos_shrine_b2, LocationType.Treasure, 207, new()),
			new Location("Chaos Shrine B4 (Air) - Legendary Chest", RegionNames.chaos_shrine_b4, LocationType.Treasure, 208, new()),

			new Location("Chaos Shrine - Garland", RegionNames.chaos_shrine, LocationType.Event, 0, new(), AccessRequirements.GarlandDefeated),
			new Location("Mount Duergar - Nerrick", RegionNames.mount_duergar, LocationType.Event, 0, new() { AccessRequirements.NitroPowder}, AccessRequirements.Canal),
			new Location("Cavern of Earth - Vampire", RegionNames.cavern_of_earth_b3, LocationType.Event, 0, new(), AccessRequirements.VampireDefeated),
			new Location("Giant's Cave - Titan", RegionNames.giants_cavern, LocationType.Event, 0, new() { AccessRequirements.StarRuby }, AccessRequirements.TitanFed),
			new Location("Cavern of Earth - Lich", RegionNames.cavern_of_earth_b5, LocationType.Event, 0, new(), AccessRequirements.EarthCrystal),
			new Location("Ryukhan Desert - Airship", RegionNames.ryukhan_desert, LocationType.Event, 0, new() { AccessRequirements.Levistone }, AccessRequirements.Airship),
			new Location("Mount Gulg - Kary", RegionNames.mount_gulg_b5, LocationType.Event, 0, new(), AccessRequirements.FireCrystal),
			new Location("Onrac - Sub Engineer", RegionNames.onrac, LocationType.Event, 0, new() { AccessRequirements.Oxyale }, AccessRequirements.Submarine),
			new Location("Sunken Shrine - Kraken", RegionNames.sunken_shrine_1f, LocationType.Event, 0, new(), AccessRequirements.WaterCrystal),
			new Location("Melmond - Dr Unne", RegionNames.melmond, LocationType.Event, 0, new() { AccessRequirements.RosettaStone }, AccessRequirements.TranslatedRosettaStone),
			new Location("Flying Fortress - Tiamat", RegionNames.flying_fortress_5f, LocationType.Event, 0, new(), AccessRequirements.AirCrystal),
			new Location("Chaos Shrine - Black Orb", RegionNames.chaos_shrine, LocationType.Event, 0, new() { AccessRequirements.EarthCrystal, AccessRequirements.FireCrystal, AccessRequirements.WaterCrystal, AccessRequirements.AirCrystal, AccessRequirements.Lute }, AccessRequirements.BlackOrbDestroyed),
			new Location("Chaos Shrine - Chaos", RegionNames.chaos_shrine_b5, LocationType.Event, 0, new(), AccessRequirements.ChaosDefeated),
		};
	}
}
