using Last.Data.Master;
using Last.Interpreter;
using RomUtilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using UnityEngine.Bindings;
using UnityEngine;

namespace FF1PRAP
{
	public class RegionNames
	{
		public const string menu = "Menu";
		public const string overworld = "Overworld";
		public const string cornelia_region = "Cornelia Region";
		public const string pravoka_region = "Pravoka Region";
		public const string innersea_region = "Innersea Region";
		public const string ice_region = "Ice Region";
		public const string crescent_region = "Crescent Region";
		public const string gulg_region = "Gulg Region";
		public const string ryukhan_desert = "Ryukhan Desert";
		public const string melmond_region = "Melmond Region";
		public const string sage_region = "Sage Region";
		public const string dragon_plains_island = "Dragon Plains Island";
		public const string dragon_forest_island = "Dragon Forest Island";
		public const string dragon_small_island = "Dragon Small Island";
		public const string dragon_marsh_island = "Dragon Marsh Island";
		public const string bahamuts_island = "Bahamut's Island";
		public const string onrac_region = "Onrac Region";
		public const string trials_region = "Trials Region";
		public const string gaia_region = "Gaia Region";
		public const string mirage_desert = "Mirage Desert";
		public const string lufenia_region = "Lufenia Region";
		public const string cornelia = "Cornelia";
		public const string pravoka = "Pravoka";
		public const string elfheim = "Elfheim";
		public const string melmond = "Melmond";
		public const string crescent_lake = "Crescent Lake";
		public const string onrac = "Onrac";
		public const string gaia = "Gaia";
		public const string lufenia = "Lufenia";
		public const string castle_cornelia_1f = "Castle Cornelia 1F";
		public const string castle_cornelia_2f = "Castle Cornelia 2F";
		public const string chaos_shrine = "Chaos Shrine";
		public const string matoyas_cave = "Matoya's Cave";
		public const string mount_duergar = "Mount Duergar";
		public const string elven_castle = "Elven Castle";
		public const string western_keep = "Western Keep";
		public const string giants_cavern = "Giant's Cavern";
		public const string sages_cave = "Sage's Cave";
		public const string caravan_outside = "Caravan Outside";
		public const string caravan_tent = "Caravan Tent";
		public const string waterfall = "Waterfall";
		public const string dragon_caves_plains = "Dragon Caves (Plains)";
		public const string dragon_caves_forest = "Dragon Caves (Forest)";
		public const string dragon_caves_top = "Dragon Caves (Top)";
		public const string dragon_caves_marsh = "Dragon Caves (Marsh)";
		public const string dragon_caves_small = "Dragon Caves (Small)";
		public const string dragon_caves_bahamut_corridor = "Dragon Caves (Bahamut Corridor)";
		public const string dragon_caves_bahamut_hall = "Dragon Caves (Bahamut Hall)";
		public const string marsh_cave_b1 = "Marsh Cave B1";
		public const string marsh_cave_b2_top = "Marsh Cave B2 (Top)";
		public const string marsh_cave_b2_bottom = "Marsh Cave B2 (Bottom)";
		public const string marsh_cave_b3 = "Marsh Cave B3";
		public const string cavern_of_earth_b1 = "Cavern of Earth B1";
		public const string cavern_of_earth_b2 = "Cavern of Earth B2";
		public const string cavern_of_earth_b3 = "Cavern of Earth B3";
		public const string cavern_of_earth_b4 = "Cavern of Earth B4";
		public const string cavern_of_earth_b5 = "Cavern of Earth B5";
		public const string mount_gulg_b1 = "Mount Gulg B1";
		public const string mount_gulg_b2 = "Mount Gulg B2";
		public const string mount_gulg_b3_corridor = "Mount Gulg B3 (Corridor)";
		public const string mount_gulg_b4_squares = "Mount Gulg B4 (Squares)";
		public const string mount_gulg_b3_maze = "Mount Gulg B3 (Maze)";
		public const string mount_gulg_b4_agama = "Mount Gulg B4 (Agama)";
		public const string mount_gulg_b5 = "Mount Gulg B5";
		public const string cavern_of_ice_b1_entrance = "Cavern of Ice B1 (Entrance)";
		public const string cavern_of_ice_b2_square = "Cavern of Ice B2 (Square)";
		public const string cavern_of_ice_b3_small = "Cavern of Ice B3 (Small)";
		public const string cavern_of_ice_b2_room = "Cavern of Ice B2 (Room)";
		public const string cavern_of_ice_b3_treasury = "Cavern of Ice B3 (Treasury)";
		public const string cavern_of_ice_b1_backdoor = "Cavern of Ice B1 (Backdoor)";
		public const string cavern_of_ice_b2_ledge = "Cavern of Ice B2 (Ledge)";
		public const string citadel_of_trials_1f = "Citadel of Trials 1F";
		public const string citadel_of_trials_2f = "Citadel of Trials 2F";
		public const string sunken_shrine_3f_split = "Sunken Shrine 3F (Split)";
		public const string sunken_shrine_4f_tfc = "Sunken Shrine 4F (TFC)";
		public const string sunken_shrine_5f = "Sunken Shrine 5F";
		public const string sunken_shrine_2f_sunken_city = "Sunken Shrine 2F (Sunken City)";
		public const string sunken_shrine_3f_small = "Sunken Shrine 3F (Small)";
		public const string sunken_shrine_4f_square = "Sunken Shrine 4F (Square)";
		public const string sunken_shrine_3f_vertical = "Sunken Shrine 3F (Vertical)";
		public const string sunken_shrine_2f_sharknado = "Sunken Shrine 2F (Sharknado)";
		public const string sunken_shrine_1f = "Sunken Shrine 1F";
		public const string mirage_tower_1f = "Mirage Tower 1F";
		public const string mirage_tower_2f = "Mirage Tower 2F";
		public const string mirage_tower_3f = "Mirage Tower 3F";
		public const string flying_fortress_1f = "Flying Fortress 1F";
		public const string flying_fortress_2f = "Flying Fortress 2F";
		public const string flying_fortress_3f = "Flying Fortress 3F";
		public const string flying_fortress_4f = "Flying Fortress 4F";
		public const string flying_fortress_5f = "Flying Fortress 5F";
		public const string chaos_shrine_1f_entrance = "Chaos Shrine 1F (Entrance)";
		public const string chaos_shrine_b1_deadend = "Chaos Shrine B1 (Deadend)";
		public const string chaos_shrine_2f_corridor = "Chaos Shrine 2F (Corridor)";
		public const string chaos_shrine_3f_plaza = "Chaos Shrine 3F (Plaza)";
		public const string chaos_shrine_2f_plaza = "Chaos Shrine 2F (Plaza)";
		public const string chaos_shrine_1f_corridor = "Chaos Shrine 1F (Corridor)";
		public const string chaos_shrine_b1_earth = "Chaos Shrine B1 (Earth)";
		public const string chaos_shrine_b2 = "Chaos Shrine B2";
		public const string chaos_shrine_b3 = "Chaos Shrine B3";
		public const string chaos_shrine_b4 = "Chaos Shrine B4";
		public const string chaos_shrine_b5 = "Chaos Shrine B5";
	}
}
