using Last.Data.Master;
using Last.Interpreter;
using RomUtilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using UnityEngine.Bindings;
using UnityEngine;

namespace FF1PRAP
{
	partial class Randomizer
    {
		public static Dictionary<int, string> FlagToLocationName = new()
		{
			{ 5, "Chaos Shrine - Unlocked Single" },
			{ 6, "Chaos Shrine - Unlocked Duo 1" },
			{ 7, "Chaos Shrine - Unlocked Duo 2" },
			{ 10, "Chaos Shrine - Locked Single" },
			{ 8, "Chaos Shrine - Locked Duo 1" },
			{ 9, "Chaos Shrine - Locked Duo 2" },
			{ 400, "Castle Cornelia - Princess" },
			{ 0, "Castle Cornelia - Treasury 1" },
			{ 1, "Castle Cornelia - Treasury 2" },
			{ 2, "Castle Cornelia - Treasury 3" },
			{ 3, "Castle Cornelia - Treasury 4" },
			{ 4, "Castle Cornelia - Treasury 5" },
			{ 505, "Castle Cornelia - Treasury Major" },
			{ 11, "Matoya's Cave - Chest 1" },
			{ 12, "Matoya's Cave - Chest 2" },
			{ 13, "Matoya's Cave - Chest 3" },
			{ 247, "Matoya's Cave - Matoya" },
			{ 401, "Pravoka - Bikke" },
			{ 24, "Marsh Cave B2 (Top) - Single" },
			{ 232, "Marsh Cave B2 (Top) - Corner" },
			{ 21, "Marsh Cave B2 (Top) - Duo 1" },
			{ 22, "Marsh Cave B2 (Top) - Duo 2" },
			{ 231, "Marsh Cave B2 (Bottom) - Leftmost Chest" },
			{ 23, "Marsh Cave B2 (Bottom) - Center Chest" },
			{ 233, "Marsh Cave B2 (Bottom) - Rightmost Chest" },
			{ 25, "Marsh Cave B3 (Bottom) - Distant Chest" },
			{ 26, "Marsh Cave B3 (Bottom) - Tetris-Z First" },
			{ 27, "Marsh Cave B3 (Bottom) - Tetris-Z Middle 1" },
			{ 234, "Marsh Cave B3 (Bottom) - Tetris-Z Middle 2" },
			{ 501, "Marsh Cave B3 (Bottom) - Tetris-Z Major" },
			{ 28, "Marsh Cave B3 (Bottom) - Tetris-Z Last" },
			{ 29, "Marsh Cave B3 (Bottom) - First Room Chest" },
			{ 235, "Marsh Cave B3 (Bottom) - Dunno Chest" },
			{ 30, "Marsh Cave B3 (Bottom) - Locked Corner" },
			{ 31, "Marsh Cave B3 (Bottom) - Locked Middle" },
			{ 32, "Marsh Cave B3 (Bottom) - Locked Cross" },
			{ 246, "Western Keep - Astos" },
			{ 18, "Western Keep - Treasury 1" },
			{ 19, "Western Keep - Treasury 2" },
			{ 20, "Western Keep - Treasury 3" },
			{ 248, "Elven Castle - Elf Prince" },
			{ 14, "Elven Castle - Treasury 1" },
			{ 15, "Elven Castle - Treasury 2" },
			{ 16, "Elven Castle - Treasury 3" },
			{ 17, "Elven Castle - Treasury 4" },
			{ 33, "Mount Duergar - Entrance 1" },
			{ 34, "Mount Duergar - Entrance 2" },
			{ 35, "Mount Duergar - Treasury 1" },
			{ 36, "Mount Duergar - Treasury 2" },
			{ 37, "Mount Duergar - Treasury 3" },
			{ 38, "Mount Duergar - Treasury 4" },
			{ 39, "Mount Duergar - Treasury 5" },
			{ 40, "Mount Duergar - Treasury 6" },
			{ 41, "Mount Duergar - Treasury 7" },
			{ 42, "Mount Duergar - Treasury 8" },
			{ 405, "Mount Duergar - Smitt" },
			{ 43, "Cavern of Earth B1 - Single" },
			{ 44, "Cavern of Earth B1 - Appendix 1" },
			{ 45, "Cavern of Earth B1 - Appendix 2" },
			{ 46, "Cavern of Earth B1 - Side Path 1" },
			{ 47, "Cavern of Earth B1 - Side Path 2" },
			{ 48, "Cavern of Earth B2 - Guarded 1" },
			{ 49, "Cavern of Earth B2 - Guarded 2" },
			{ 50, "Cavern of Earth B2 - Guarded 3" },
			{ 51, "Cavern of Earth B2 - Side Room 1" },
			{ 52, "Cavern of Earth B2 - Side Room 2" },
			{ 53, "Cavern of Earth B2 - Side Room 3" },
			{ 54, "Cavern of Earth B3 - Side Room" },
			{ 55, "Cavern of Earth B3 - TFC" },
			{ 56, "Cavern of Earth B3 - Asher Trunk" },
			{ 57, "Cavern of Earth B3 - Vampire's Closet" },
			{ 508, "Cavern of Earth B3 - Vampire's Chest" },
			{ 58, "Cavern of Earth B4 - Armory 1" },
			{ 59, "Cavern of Earth B4 - Armory 2" },
			{ 60, "Cavern of Earth B4 - Armory 3" },
			{ 61, "Cavern of Earth B4 - Armory 4" },
			{ 62, "Cavern of Earth B4 - Armory 5" },
			{ 63, "Cavern of Earth B4 - Lich's Closet 1" },
			{ 64, "Cavern of Earth B4 - Lich's Closet 2" },
			{ 65, "Cavern of Earth B4 - Lich's Closet 3" },
			{ 241, "Giant's Cave - Chest 1" },
			{ 242, "Giant's Cave - Chest 2" },
			{ 243, "Giant's Cave - Chest 3" },
			{ 244, "Giant's Cave - Chest 4" },
			{ 253, "Sage's Cave - Sarda" },
			{ 402, "Crescent Lake - Canoe Sage" },
			{ 66, "Mount Gulg B2 - Guarded" },
			{ 67, "Mount Gulg B2 - Center" },
			{ 68, "Mount Gulg B2 - Hairpins" },
			{ 69, "Mount Gulg B2 - Shortpins" },
			{ 70, "Mount Gulg B2 - Vertpins 1" },
			{ 71, "Mount Gulg B2 - Vertpins 2" },
			{ 72, "Mount Gulg B2 - Armory 1" },
			{ 73, "Mount Gulg B2 - Armory 2" },
			{ 74, "Mount Gulg B2 - Armory 3" },
			{ 75, "Mount Gulg B2 - Armory 4" },
			{ 76, "Mount Gulg B2 - Armory 5" },
			{ 77, "Mount Gulg B2 - Armory 6" },
			{ 78, "Mount Gulg B2 - Armory 7" },
			{ 79, "Mount Gulg B2 - Armory 8" },
			{ 80, "Mount Gulg B2 - Armory 9" },
			{ 81, "Mount Gulg B2 - Armory 10" },
			{ 82, "Mount Gulg B2 - Armory 11" },
			{ 83, "Mount Gulg B2 - Armory 12" },
			{ 84, "Mount Gulg B4 - Entrance 1" },
			{ 85, "Mount Gulg B4 - Entrance 2" },
			{ 86, "Mount Gulg B4 - First Greed" },
			{ 87, "Mount Gulg B4 - Worm Room 1" },
			{ 88, "Mount Gulg B4 - Worm Room 2" },
			{ 89, "Mount Gulg B4 - Worm Room 3" },
			{ 90, "Mount Gulg B4 - Worm Room 4" },
			{ 91, "Mount Gulg B4 - Worm Room 5" },
			{ 92, "Mount Gulg B4 - Second Greed 1" },
			{ 93, "Mount Gulg B4 - Second Greed 2" },
			{ 94, "Mount Gulg B4 - Side Room 1" },
			{ 95, "Mount Gulg B4 - Side Room 2" },
			{ 236, "Mount Gulg B4 - Side Room 3" },
			{ 96, "Mount Gulg B4 - Last Room 1" },
			{ 97, "Mount Gulg B4 - Last Room 2" },
			{ 98, "Mount Gulg B5 - West Room" },
			{ 237, "Mount Gulg B5 - Northeast Room" },
			{ 238, "Mount Gulg B5 - East Room" },
			{ 239, "Mount Gulg B5 - Southeast Room" },
			{ 104, "Cavern of Ice B2 - Chest 1" },
			{ 105, "Cavern of Ice B2 - Chest 2" },
			{ 254, "Cavern of Ice B2 - Eye's Treasure" },
			{ 106, "Cavern of Ice B3 - Ice Dragon Room 1" },
			{ 107, "Cavern of Ice B3 - Ice Dragon Room 2" },
			{ 108, "Cavern of Ice B3 - Six-Pack 1" },
			{ 109, "Cavern of Ice B3 - Six-Pack 2" },
			{ 110, "Cavern of Ice B3 - Six-Pack 3" },
			{ 111, "Cavern of Ice B3 - Six-Pack 4" },
			{ 112, "Cavern of Ice B3 - Six-Pack 5" },
			{ 113, "Cavern of Ice B3 - Six-Pack 6" },
			{ 99, "Cavern of Ice B1 - Greed 1" },
			{ 100, "Cavern of Ice B1 - Greed 2" },
			{ 101, "Cavern of Ice B1 - Drop Room 1" },
			{ 102, "Cavern of Ice B1 - Drop Room 2" },
			{ 103, "Cavern of Ice B1 - Drop Room 3" },
			{ 240, "Citadel of Trials 2F - Side Chest" },
			{ 210, "Citadel of Trials 3F - Single" },
			{ 211, "Citadel of Trials 3F - Three-Pack 1" },
			{ 212, "Citadel of Trials 3F - Three-Pack 2" },
			{ 213, "Citadel of Trials 3F - Three-Pack 3" },
			{ 214, "Citadel of Trials 3F - Four-Pack 1" },
			{ 215, "Citadel of Trials 3F - Four-Pack 2" },
			{ 216, "Citadel of Trials 3F - Four-Pack 3" },
			{ 217, "Citadel of Trials 3F - Four-Pack 4" },
			{ 512, "Citadel of Trials 3F - Mouse Chest" },
			{ 224, "Dragon Caves (Forest) - Entrance 1" },
			{ 225, "Dragon Caves (Forest) - Entrance 2" },
			{ 226, "Dragon Caves (Forest) - Entrance 3" },
			{ 227, "Dragon Caves (Forest) - West Room 1" },
			{ 228, "Dragon Caves (Forest) - West Room 2" },
			{ 229, "Dragon Caves (Forest) - West Room 3" },
			{ 230, "Dragon Caves (Forest) - West Room 4" },
			{ 221, "Dragon Caves (Marsh) - Chest 1" },
			{ 222, "Dragon Caves (Marsh) - Chest 2" },
			{ 223, "Dragon Caves (Marsh) - Chest 3" },
			{ 218, "Dragon Caves (Plains) - Entrance" },
			{ 219, "Dragon Caves (Plains) - Duo 1" },
			{ 220, "Dragon Caves (Plains) - Duooo 2" },
			{ 407, "Dragon Caves - Bahamut" },
			{ 406, "Onrac Desert - Caravan" },
			{ 114, "Waterfall Caverns - Chest 1" },
			{ 115, "Waterfall Caverns - Chest 2" },
			{ 116, "Waterfall Caverns - Chest 3" },
			{ 117, "Waterfall Caverns - Chest 4" },
			{ 118, "Waterfall Caverns - Chest 5" },
			{ 119, "Waterfall Caverns - Chest 6" },
			{ 404, "Waterfall Caverns - CubeBot" },
			{ 403, "Gaia - Fairy" },
			{ 130, "Sunken Shrine 3F (Split) - Kraken Side Chest" },
			{ 131, "Sunken Shrine 3F (Split) - Mermaids Side Chest" },
			{ 134, "Sunken Shrine 4F (TFC) - TFC" },
			{ 135, "Sunken Shrine 4F (TFC) - TFC North" },
			{ 136, "Sunken Shrine 4F (TFC) - Side Corner" },
			{ 137, "Sunken Shrine 4F (TFC) - First Greed" },
			{ 138, "Sunken Shrine 4F (TFC) - Second Greed" },
			{ 139, "Sunken Shrine 5F - Passby" },
			{ 140, "Sunken Shrine 5F - Bubbles 1" },
			{ 141, "Sunken Shrine 5F - Bubbles 2" },
			{ 142, "Sunken Shrine 5F - Far Room 1" },
			{ 143, "Sunken Shrine 5F - Far Room 2" },
			{ 507, "Sunken Shrine 5F - Far Major" },
			{ 144, "Sunken Shrine 5F - Entrance 1" },
			{ 145, "Sunken Shrine 5F - Entrance 2" },
			{ 146, "Sunken Shrine 5F - Entrance 3" },
			{ 147, "Sunken Shrine 5F - Four-Corner 1" },
			{ 148, "Sunken Shrine 5F - Four-Corner 2" },
			{ 149, "Sunken Shrine 5F - Four-Corner 3" },
			{ 150, "Sunken Shrine 5F - Four-Corner 4" },
			{ 132, "Sunken Shrine 3F (Vertical) - Top Chest" },
			{ 133, "Sunken Shrine 3F (Vertical) - Bottom Chest" },
			{ 120, "Sunken Shrine 2F (Sharknado) - Dengbait 1" },
			{ 121, "Sunken Shrine 2F (Sharknado) - Dengbait 2" },
			{ 122, "Sunken Shrine 2F (Sharknado) - Side Corner 1" },
			{ 123, "Sunken Shrine 2F (Sharknado) - Side Corner 2" },
			{ 124, "Sunken Shrine 2F (Sharknado) - Side Corner 3" },
			{ 125, "Sunken Shrine 2F (Sharknado) - Exit" },
			{ 126, "Sunken Shrine 2F (Sharknado) - Shark 1" },
			{ 127, "Sunken Shrine 2F (Sharknado) - Shark 2" },
			{ 128, "Sunken Shrine 2F (Sharknado) - Shark 3" },
			{ 129, "Sunken Shrine 2F (Sharknado) - Shark 4" },
			{ 255, "Lufenia - Lufenian Man" },
			{ 151, "Mirage Tower 1F - Chest 1" },
			{ 152, "Mirage Tower 1F - Chest 2" },
			{ 153, "Mirage Tower 1F - Chest 3" },
			{ 154, "Mirage Tower 1F - Chest 4" },
			{ 155, "Mirage Tower 1F - Chest 5" },
			{ 156, "Mirage Tower 1F - Chest 6" },
			{ 157, "Mirage Tower 1F - Chest 7" },
			{ 158, "Mirage Tower 1F - Chest 8" },
			{ 159, "Mirage Tower 2F - Lesser 1" },
			{ 160, "Mirage Tower 2F - Lesser 2" },
			{ 161, "Mirage Tower 2F - Lesser 3" },
			{ 162, "Mirage Tower 2F - Lesser 4" },
			{ 163, "Mirage Tower 2F - Lesser 5" },
			{ 164, "Mirage Tower 2F - Greater 1" },
			{ 165, "Mirage Tower 2F - Greater 2" },
			{ 166, "Mirage Tower 2F - Greater 3" },
			{ 167, "Mirage Tower 2F - Greater 4" },
			{ 168, "Mirage Tower 2F - Greater 5" },
			{ 178, "Flying Fortress 1F - Solo" },
			{ 169, "Flying Fortress 1F - West Room 1" },
			{ 170, "Flying Fortress 1F - West Room 2" },
			{ 171, "Flying Fortress 1F - West Room 3" },
			{ 172, "Flying Fortress 1F - West Room 4" },
			{ 173, "Flying Fortress 1F - East Room 1" },
			{ 174, "Flying Fortress 1F - East Room 2" },
			{ 175, "Flying Fortress 1F - East Room 3" },
			{ 176, "Flying Fortress 1F - East Room 4" },
			{ 177, "Flying Fortress 1F - East Room 5" },
			{ 179, "Flying Fortress 2F - Cheap Room 1" },
			{ 180, "Flying Fortress 2F - Cheap Room 2" },
			{ 181, "Flying Fortress 2F - Vault 1" },
			{ 182, "Flying Fortress 2F - Vault 2" },
			{ 250, "Flying Fortress 2F - Major" },
			{ 183, "Flying Fortress 2F - Gauntlet Room" },
			{ 184, "Flying Fortress 2F - Ribbon Room 1" },
			{ 185, "Flying Fortress 2F - Ribbon Room 2" },
			{ 186, "Flying Fortress 2F - Wardrobe 1" },
			{ 187, "Flying Fortress 2F - Wardrobe 2" },
			{ 188, "Flying Fortress 3F - CC's Gambit 1" },
			{ 189, "Flying Fortress 3F - CC's Gambit 2" },
			{ 190, "Flying Fortress 3F - CC's Gambit 3" },
			{ 191, "Flying Fortress 3F - CC's Gambit 4" },
			{ 192, "Flying Fortress 3F - Six-Pack 1" },
			{ 193, "Flying Fortress 3F - Six-Pack 2" },
			{ 194, "Flying Fortress 3F - Six-Pack 3" },
			{ 195, "Flying Fortress 3F - Six-Pack 4" },
			{ 196, "Flying Fortress 3F - Six-Pack 5" },
			{ 197, "Flying Fortress 3F - Six-Pack 6" },
			{ 198, "Flying Fortress 3F - Exit 1" },
			{ 199, "Flying Fortress 3F - Exit 2" },
			{ 200, "Flying Fortress 3F - Exit 3" },
			{ 201, "Flying Fortress 3F - Exit 4" },
			{ 202, "Chaos Shrine 3F - Validation 1" },
			{ 203, "Chaos Shrine 3F - Validation 2" },
			{ 204, "Chaos Shrine B2 (Fire) - Right Chest" },
			{ 205, "Chaos Shrine B2 (Fire) - Left Chest" },
			{ 206, "Chaos Shrine B2 (Fire) - Eastern Vault" },
			{ 207, "Chaos Shrine B2 (Fire) - Southern Vault" },
			{ 208, "Chaos Shrine B4 (Air) - Legendary Chest" },
		};
	}
}
