using Last.Data.Master;
using Last.Interpreter;
using RomUtilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using UnityEngine.Bindings;
using UnityEngine;

namespace FF1PRAP
{
	partial class Randomizer
    {
		public static Dictionary<string, ItemData> ItemNameToData = new()
		{
			{ "Leather Cap", new ItemData() { Id = 175, Qty = 1 } },
			{ "Potion", new ItemData() { Id = 2, Qty = 1 } },
			{ "Tent", new ItemData() { Id = 18, Qty = 1 } },
			{ "Rune Blade", new ItemData() { Id = 75, Qty = 1 } },
			{ "Werebuster", new ItemData() { Id = 74, Qty = 1 } },
			{ "Gold Needle", new ItemData() { Id = 14, Qty = 1 } },
			{ "Lute", new ItemData() { Id = 45, Qty = 1 } },
			{ "Antidote", new ItemData() { Id = 11, Qty = 1 } },
			{ "Jolt Tonic", new ItemData() { Id = 48, Qty = 1 } },
			{ "Ship", new ItemData() { Id = 44, Qty = 1 } },
			{ "Dagger", new ItemData() { Id = 64, Qty = 1 } },
			{ "1180 Gil", new ItemData() { Id = 1, Qty = 1180 } },
			{ "1120 Gil", new ItemData() { Id = 1, Qty = 1120 } },
			{ "Broadsword", new ItemData() { Id = 73, Qty = 1 } },
			{ "Phoenix Down", new ItemData() { Id = 10, Qty = 1 } },
			{ "1045 Gil", new ItemData() { Id = 1, Qty = 1045 } },
			{ "Cottage", new ItemData() { Id = 19, Qty = 1 } },
			{ "Copper Armlet", new ItemData() { Id = 156, Qty = 1 } },
			{ "Crown", new ItemData() { Id = 46, Qty = 1 } },
			{ "1135 Gil", new ItemData() { Id = 1, Qty = 1135 } },
			{ "Silver Armlet", new ItemData() { Id = 157, Qty = 1 } },
			{ "1020 Gil", new ItemData() { Id = 1, Qty = 1020 } },
			{ "Crystal Eye", new ItemData() { Id = 47, Qty = 1 } },
			{ "Mythril Hammer", new ItemData() { Id = 115, Qty = 1 } },
			{ "800 Gil", new ItemData() { Id = 1, Qty = 800 } },
			{ "700 Gil", new ItemData() { Id = 1, Qty = 700 } },
			{ "Bronze Gloves", new ItemData() { Id = 192, Qty = 1 } },
			{ "Mystic Key", new ItemData() { Id = 49, Qty = 1 } },
			{ "Falchion", new ItemData() { Id = 97, Qty = 1 } },
			{ "Steel Gloves", new ItemData() { Id = 193, Qty = 1 } },
			{ "Power Staff", new ItemData() { Id = 120, Qty = 1 } },
			{ "Saber", new ItemData() { Id = 72, Qty = 1 } },
			{ "Mythril Knife", new ItemData() { Id = 65, Qty = 1 } },
			{ "Iron Armor", new ItemData() { Id = 148, Qty = 1 } },
			{ "Nitro Powder", new ItemData() { Id = 50, Qty = 1 } },
			{ "575 Gil", new ItemData() { Id = 1, Qty = 575 } },
			{ "450 Gil", new ItemData() { Id = 1, Qty = 450 } },
			{ "Excalibur", new ItemData() { Id = 92, Qty = 1 } },
			{ "Great Helm", new ItemData() { Id = 185, Qty = 1 } },
			{ "Wyrmkiller", new ItemData() { Id = 76, Qty = 1 } },
			{ "Ether", new ItemData() { Id = 5, Qty = 1 } },
			{ "Mythril Mail", new ItemData() { Id = 147, Qty = 1 } },
			{ "1975 Gil", new ItemData() { Id = 1, Qty = 1975 } },
			{ "795 Gil", new ItemData() { Id = 1, Qty = 795 } },
			{ "880 Gil", new ItemData() { Id = 1, Qty = 880 } },
			{ "Leather Shield", new ItemData() { Id = 161, Qty = 1 } },
			{ "5000 Gil", new ItemData() { Id = 1, Qty = 5000 } },
			{ "Coral Sword", new ItemData() { Id = 77, Qty = 1 } },
			{ "330 Gil", new ItemData() { Id = 1, Qty = 330 } },
			{ "Sleeping Bag", new ItemData() { Id = 17, Qty = 1 } },
			{ "3400 Gil", new ItemData() { Id = 1, Qty = 3400 } },
			{ "Star Ruby", new ItemData() { Id = 53, Qty = 1 } },
			{ "Staff", new ItemData() { Id = 118, Qty = 1 } },
			{ "1520 Gil", new ItemData() { Id = 1, Qty = 1520 } },
			{ "5450 Gil", new ItemData() { Id = 1, Qty = 5450 } },
			{ "1455 Gil", new ItemData() { Id = 1, Qty = 1455 } },
			{ "Mythril Shield", new ItemData() { Id = 164, Qty = 1 } },
			{ "1250 Gil", new ItemData() { Id = 1, Qty = 1250 } },
			{ "Great Axe", new ItemData() { Id = 107, Qty = 1 } },
			{ "620 Gil", new ItemData() { Id = 1, Qty = 620 } },
			{ "Mythril Helm", new ItemData() { Id = 187, Qty = 1 } },
			{ "Earth Rod", new ItemData() { Id = 54, Qty = 1 } },
			{ "Canoe", new ItemData() { Id = 61, Qty = 1 } },
			{ "Clothes", new ItemData() { Id = 134, Qty = 1 } },
			{ "Flame Sword", new ItemData() { Id = 83, Qty = 1 } },
			{ "Levistone", new ItemData() { Id = 55, Qty = 1 } },
			{ "Ice Armor", new ItemData() { Id = 149, Qty = 1 } },
			{ "Mythril Gloves", new ItemData() { Id = 197, Qty = 1 } },
			{ "7900 Gil", new ItemData() { Id = 1, Qty = 7900 } },
			{ "9900 Gil", new ItemData() { Id = 1, Qty = 9900 } },
			{ "5454 Gil", new ItemData() { Id = 1, Qty = 5454 } },
			{ "12350 Gil", new ItemData() { Id = 1, Qty = 12350 } },
			{ "10000 Gil", new ItemData() { Id = 1, Qty = 10000 } },
			{ "9500 Gil", new ItemData() { Id = 1, Qty = 9500 } },
			{ "Ice Shield", new ItemData() { Id = 165, Qty = 1 } },
			{ "Healing Staff", new ItemData() { Id = 119, Qty = 1 } },
			{ "Ruby Armlet", new ItemData() { Id = 158, Qty = 1 } },
			{ "Ice Brand", new ItemData() { Id = 86, Qty = 1 } },
			{ "7340 Gil", new ItemData() { Id = 1, Qty = 7340 } },
			{ "Gauntlets", new ItemData() { Id = 194, Qty = 1 } },
			{ "Rat's Tail", new ItemData() { Id = 57, Qty = 1 } },
			{ "2750 Gil", new ItemData() { Id = 1, Qty = 2750 } },
			{ "2000 Gil", new ItemData() { Id = 1, Qty = 2000 } },
			{ "X-Potion", new ItemData() { Id = 4, Qty = 1 } },
			{ "Elixir", new ItemData() { Id = 8, Qty = 1 } },
			{ "1000 Gil", new ItemData() { Id = 1, Qty = 1000 } },
			{ "Dry Ether", new ItemData() { Id = 7, Qty = 1 } },
			{ "Great Sword", new ItemData() { Id = 79, Qty = 1 } },
			{ "4150 Gil", new ItemData() { Id = 1, Qty = 4150 } },
			{ "1295 Gil", new ItemData() { Id = 1, Qty = 1295 } },
			{ "Hi-Potion", new ItemData() { Id = 3, Qty = 1 } },
			{ "1760 Gil", new ItemData() { Id = 1, Qty = 1760 } },
			{ "Mythril Axe", new ItemData() { Id = 109, Qty = 1 } },
			{ "1380 Gil", new ItemData() { Id = 1, Qty = 1380 } },
			{ "Flame Shield", new ItemData() { Id = 166, Qty = 1 } },
			{ "1150 Gil", new ItemData() { Id = 1, Qty = 1150 } },
			{ "1155 Gil", new ItemData() { Id = 1, Qty = 1155 } },
			{ "Flame Mail", new ItemData() { Id = 150, Qty = 1 } },
			{ "Wizard's Staff", new ItemData() { Id = 123, Qty = 1 } },
			{ "Ribbon", new ItemData() { Id = 183, Qty = 1 } },
			{ "6400 Gil", new ItemData() { Id = 1, Qty = 6400 } },
			{ "13450 Gil", new ItemData() { Id = 1, Qty = 13450 } },
			{ "Defender", new ItemData() { Id = 87, Qty = 1 } },
			{ "Warp Cube", new ItemData() { Id = 58, Qty = 1 } },
			{ "Oxyale", new ItemData() { Id = 60, Qty = 1 } },
			{ "Diamond Armor", new ItemData() { Id = 153, Qty = 1 } },
			{ "1300 Gil", new ItemData() { Id = 1, Qty = 1300 } },
			{ "Light Axe", new ItemData() { Id = 110, Qty = 1 } },
			{ "Mage's Staff", new ItemData() { Id = 121, Qty = 1 } },
			{ "9000 Gil", new ItemData() { Id = 1, Qty = 9000 } },
			{ "Diamond Armlet", new ItemData() { Id = 160, Qty = 1 } },
			{ "Diamond Shield", new ItemData() { Id = 168, Qty = 1 } },
			{ "Diamond Gloves", new ItemData() { Id = 198, Qty = 1 } },
			{ "Diamond Helm", new ItemData() { Id = 188, Qty = 1 } },
			{ "Rosetta Stone", new ItemData() { Id = 52, Qty = 1 } },
			{ "1110 Gil", new ItemData() { Id = 1, Qty = 1110 } },
			{ "1450 Gil", new ItemData() { Id = 1, Qty = 1450 } },
			{ "8135 Gil", new ItemData() { Id = 1, Qty = 8135 } },
			{ "7690 Gil", new ItemData() { Id = 1, Qty = 7690 } },
			{ "Giant's Gloves", new ItemData() { Id = 195, Qty = 1 } },
			{ "1385 Gil", new ItemData() { Id = 1, Qty = 1385 } },
			{ "Chime", new ItemData() { Id = 56, Qty = 1 } },
			{ "Healing Helm", new ItemData() { Id = 186, Qty = 1 } },
			{ "18010 Gil", new ItemData() { Id = 1, Qty = 18010 } },
			{ "Vorpal Sword", new ItemData() { Id = 82, Qty = 1 } },
			{ "Aegis Shield", new ItemData() { Id = 170, Qty = 1 } },
			{ "Thor's Hammer", new ItemData() { Id = 116, Qty = 1 } },
			{ "13000 Gil", new ItemData() { Id = 1, Qty = 13000 } },
			{ "7600 Gil", new ItemData() { Id = 1, Qty = 7600 } },
			{ "Sun Blade", new ItemData() { Id = 89, Qty = 1 } },
			{ "Dragon Mail", new ItemData() { Id = 154, Qty = 1 } },
			{ "Razer", new ItemData() { Id = 80, Qty = 1 } },
			{ "6720 Gil", new ItemData() { Id = 1, Qty = 6720 } },
			{ "Protect Ring", new ItemData() { Id = 202, Qty = 1 } },
			{ "Black Robe", new ItemData() { Id = 137, Qty = 1 } },
			{ "White Robe", new ItemData() { Id = 136, Qty = 1 } },
			{ "Adamantite", new ItemData() { Id = 51, Qty = 1 } },
			{ "Protect Cloak", new ItemData() { Id = 173, Qty = 1 } },
			{ "Sasuke's Blade", new ItemData() { Id = 100, Qty = 1 } },
			{ "Masamune", new ItemData() { Id = 103, Qty = 1 } },
			{ "Bottled Faerie", new ItemData() { Id = 59, Qty = 1 } },
			{ "All Promotion Jobs", new ItemData() { Id = 500, Qty = 1 } },
			{ "Knight Job", new ItemData() { Id = 501, Qty = 1 } },
			{ "Ninja Job", new ItemData() { Id = 502, Qty = 1 } },
			{ "Master Job", new ItemData() { Id = 503, Qty = 1 } },
			{ "Red Wizard Job", new ItemData() { Id = 504, Qty = 1 } },
			{ "White Wizard Job", new ItemData() { Id = 505, Qty = 1 } },
			{ "Black Wizard Job", new ItemData() { Id = 506, Qty = 1 } },
			{ "Airship", new ItemData() { Id = 507, Qty = 1 } },
			{ "Lute Tablature", new ItemData() { Id = 508, Qty = 1 } },
		};
	}
}
