using Last.Data.Master;
using Last.Interpreter;
using RomUtilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using UnityEngine.Bindings;
using UnityEngine;

namespace FF1PRAP
{
	public struct Teleporter
	{
		public string Name;
		public string MapGroup;
		public string MapName;
		public int MapId;
		public int PointId;
		public bool IsScript;
	}
	partial class Randomizer
    {
		public static List<Teleporter> Teleporters = new()
		{
			new() { Name = "Overworld - Castle Cornelia", MapGroup = "map_10010", MapName = "Map_10010", MapId = 1, PointId = 1 },
			new() { Name = "Overworld - Cornelia", MapGroup = "map_10010", MapName = "Map_10010", MapId = 1, PointId = 2 },
			new() { Name = "Overworld - Chaos Shrine", MapGroup = "map_10010", MapName = "Map_10010", MapId = 1, PointId = 3 },
			new() { Name = "Overworld - Matoya's Cave", MapGroup = "map_10010", MapName = "Map_10010", MapId = 1, PointId = 4 },
			new() { Name = "Overworld - Pravoka", MapGroup = "map_10010", MapName = "Map_10010", MapId = 1, PointId = 5 },
			new() { Name = "Overworld - Mount Duergar", MapGroup = "map_10010", MapName = "Map_10010", MapId = 1, PointId = 6 },
			new() { Name = "Overworld - Elfheim", MapGroup = "map_10010", MapName = "Map_10010", MapId = 1, PointId = 7 },
			new() { Name = "Overworld - Elven Castle", MapGroup = "map_10010", MapName = "Map_10010", MapId = 1, PointId = 8 },
			new() { Name = "Overworld - Western Keep", MapGroup = "map_10010", MapName = "Map_10010", MapId = 1, PointId = 9 },
			new() { Name = "Overworld - Marsh Cave", MapGroup = "map_10010", MapName = "Map_10010", MapId = 1, PointId = 10 },
			new() { Name = "Overworld - Melmond", MapGroup = "map_10010", MapName = "Map_10010", MapId = 1, PointId = 11 },
			new() { Name = "Overworld - Cavern of Earth", MapGroup = "map_10010", MapName = "Map_10010", MapId = 1, PointId = 12 },
			new() { Name = "Overworld - Giant's Cavern West", MapGroup = "map_10010", MapName = "Map_10010", MapId = 1, PointId = 13 },
			new() { Name = "Overworld - Giant's Cavern East", MapGroup = "map_10010", MapName = "Map_10010", MapId = 1, PointId = 14 },
			new() { Name = "Overworld - Sage's Cave", MapGroup = "map_10010", MapName = "Map_10010", MapId = 1, PointId = 15 },
			new() { Name = "Overworld - Crescent Lake", MapGroup = "map_10010", MapName = "Map_10010", MapId = 1, PointId = 16 },
			new() { Name = "Overworld - Mount Gulg", MapGroup = "map_10010", MapName = "Map_10010", MapId = 1, PointId = 17 },
			new() { Name = "Overworld - Cavern of Ice", MapGroup = "map_10010", MapName = "Map_10010", MapId = 1, PointId = 18 },
			new() { Name = "Overworld - Dragon Caves (Plains)", MapGroup = "map_10010", MapName = "Map_10010", MapId = 1, PointId = 19 },
			new() { Name = "Overworld - Dragon Caves (Top)", MapGroup = "map_10010", MapName = "Map_10010", MapId = 1, PointId = 20 },
			new() { Name = "Overworld - Dragon Caves (Marsh)", MapGroup = "map_10010", MapName = "Map_10010", MapId = 1, PointId = 21 },
			new() { Name = "Overworld - Dragon Caves (Small)", MapGroup = "map_10010", MapName = "Map_10010", MapId = 1, PointId = 22 },
			new() { Name = "Overworld - Dragon Caves (Forest)", MapGroup = "map_10010", MapName = "Map_10010", MapId = 1, PointId = 23 },
			new() { Name = "Overworld - Dragon Caves (Bahamut)", MapGroup = "map_10010", MapName = "Map_10010", MapId = 1, PointId = 24 },
			new() { Name = "Overworld - Citadel of Trials", MapGroup = "map_10010", MapName = "Map_10010", MapId = 1, PointId = 25 },
			new() { Name = "Overworld - Onrac", MapGroup = "map_10010", MapName = "Map_10010", MapId = 1, PointId = 26 },
			new() { Name = "Overworld - Caravan", MapGroup = "map_10010", MapName = "Map_10010", MapId = 1, PointId = 27 },
			new() { Name = "Overworld - Gaia", MapGroup = "map_10010", MapName = "Map_10010", MapId = 1, PointId = 28 },
			new() { Name = "Overworld - Waterfall", MapGroup = "map_10010", MapName = "Map_10010", MapId = 1, PointId = 29 },
			new() { Name = "Overworld - Lufenia", MapGroup = "map_10010", MapName = "Map_10010", MapId = 1, PointId = 30 },
			new() { Name = "Overworld - Mirage Tower", MapGroup = "map_10010", MapName = "Map_10010", MapId = 1, PointId = 31 },

			new() { Name = "Castle Cornelia 1F - Entrance", MapGroup = "map_20011", MapName = "Map_20011_1", MapId = 2, PointId = 1 },
			new() { Name = "Castle Cornelia 1F - Stairs", MapGroup = "map_20011", MapName = "Map_20011_1", MapId = 2, PointId = 2 },
			new() { Name = "Castle Cornelia 2F - Stairs", MapGroup = "map_20011", MapName = "Map_20011_2", MapId = 3, PointId = 1 },
			new() { Name = "Castle Cornelia - Throne Room", MapGroup = "map_20011", MapName = "Map_20011_2", MapId = 3, PointId = 101 },
			new() { Name = "Cornelia - Entrance", MapGroup = "map_20020", MapName = "Map_20020", MapId = 4, PointId = 1 },

			new() { Name = "Matoya's Cave - Entrance", MapGroup = "map_20031", MapName = "Map_20031_1", MapId = 12, PointId = 1 },
			new() { Name = "Pravoka - Entrance", MapGroup = "map_20040", MapName = "Map_20040", MapId = 13, PointId = 1 },

			new() { Name = "Mount Duergar - Entrance", MapGroup = "map_20051", MapName = "Map_20051_1", MapId = 21, PointId = 1 },
			new() { Name = "Elfheim - Entrance", MapGroup = "map_20060", MapName = "Map_20060", MapId = 22, PointId = 1 },

			new() { Name = "Elven Castle - Entrance", MapGroup = "map_20071", MapName = "Map_20071_1", MapId = 32, PointId = 1 },
			new() { Name = "Western Keep - Entrance", MapGroup = "map_20081", MapName = "Map_20081_1", MapId = 33, PointId = 1 },
			new() { Name = "Melmond - Entrance", MapGroup = "map_20090", MapName = "Map_20090", MapId = 34, PointId = 1 },

			new() { Name = "Sage's Cave - Entrance", MapGroup = "map_20101", MapName = "Map_20101_1", MapId = 40, PointId = 1 },
			new() { Name = "Crescent Lake - Entrance", MapGroup = "map_20110", MapName = "Map_20110", MapId = 41, PointId = 1 },

			new() { Name = "Dragon Caves (Plains) - Entrance", MapGroup = "map_20121", MapName = "Map_20121_1", MapId = 49, PointId = 1 },
			new() { Name = "Dragon Caves (Top) - Entrance", MapGroup = "map_20121", MapName = "Map_20121_1", MapId = 49, PointId = 2 },
			new() { Name = "Dragon Caves (Marsh) - Entrance", MapGroup = "map_20121", MapName = "Map_20121_1", MapId = 49, PointId = 3 },
			new() { Name = "Dragon Caves (Small) - Entrance", MapGroup = "map_20121", MapName = "Map_20121_1", MapId = 49, PointId = 4 },
			new() { Name = "Dragon Caves (Forest) - Entrance", MapGroup = "map_20121", MapName = "Map_20121_1", MapId = 49, PointId = 5 },
			new() { Name = "Dragon Caves (Bahamut) - Entrance", MapGroup = "map_20121", MapName = "Map_20121_2", MapId = 50, PointId = 1 },
			new() { Name = "Dragon Caves (Bahamut) - Bottom Stairs", MapGroup = "map_20121", MapName = "Map_20121_2", MapId = 50, PointId = 2 },
			new() { Name = "Dragon Caves (Bahamut) - Bahamut Hall", MapGroup = "map_20121", MapName = "Map_20121_3", MapId = 51, PointId = 1 },
			new() { Name = "Onrac - Entrance", MapGroup = "map_20130", MapName = "Map_20130", MapId = 52, PointId = 1 },
			new() { Name = "Onrac - Submarine Dock", MapGroup = "map_20130", MapName = "Map_20130", MapId = 52, PointId = 101 },

			new() { Name = "Caravan - Entrance", MapGroup = "map_20140", MapName = "Map_20140", MapId = 58, PointId = 1 },
			new() { Name = "Caravan - Outside Tent", MapGroup = "map_20140", MapName = "Map_20140", MapId = 58, PointId = 2 },
			new() { Name = "Caravan - Inside Tent", MapGroup = "map_20141", MapName = "Map_20141_1", MapId = 59, PointId = 1 },
			new() { Name = "Gaia - Entrance", MapGroup = "map_20150", MapName = "Map_20150", MapId = 60, PointId = 1 },

			new() { Name = "Lufenia - Entrance", MapGroup = "map_20160", MapName = "Map_20160", MapId = 70, PointId = 1 },

			new() { Name = "Chaos Shrine - Entrance", MapGroup = "map_30011", MapName = "Map_30011_1", MapId = 72, PointId = 1 },
			new() { Name = "Chaos Shrine - Black Orb Warp", MapGroup = "map_30011", MapName = "Map_30011_1", MapId = 72, PointId = 2 },
			new() { Name = "Marsh Cave B1 - Entrance", MapGroup = "map_30021", MapName = "Map_30021_1", MapId = 73, PointId = 1 },
			new() { Name = "Marsh Cave B1 - Top Stairs", MapGroup = "map_30021", MapName = "Map_30021_1", MapId = 73, PointId = 2 },
			new() { Name = "Marsh Cave B1 - Bottom Stairs", MapGroup = "map_30021", MapName = "Map_30021_1", MapId = 73, PointId = 3 },
			new() { Name = "Marsh Cave B2 - Entrance", MapGroup = "map_30021", MapName = "Map_30021_2", MapId = 74, PointId = 1 },
			new() { Name = "Marsh Cave B2 - Upper Stairs", MapGroup = "map_30021", MapName = "Map_30021_2", MapId = 74, PointId = 2 },
			new() { Name = "Marsh Cave B2 - Lower Stairs", MapGroup = "map_30021", MapName = "Map_30021_2", MapId = 74, PointId = 3 },
			new() { Name = "Marsh Cave B3 - Entrance", MapGroup = "map_30021", MapName = "Map_30021_3", MapId = 75, PointId = 1 },
			new() { Name = "Cavern of Earth B1 - Center Stairs", MapGroup = "map_30031", MapName = "Map_30031_1", MapId = 76, PointId = 1 },
			new() { Name = "Cavern of Earth B1 - Right Stairs", MapGroup = "map_30031", MapName = "Map_30031_1", MapId = 76, PointId = 2 },
			new() { Name = "Cavern of Earth B2 - Left Stairs", MapGroup = "map_30031", MapName = "Map_30031_2", MapId = 77, PointId = 1 },
			new() { Name = "Cavern of Earth B2 - Right Stairs", MapGroup = "map_30031", MapName = "Map_30031_2", MapId = 77, PointId = 2 },
			new() { Name = "Cavern of Earth B3 - Bottom Stairs", MapGroup = "map_30031", MapName = "Map_30031_3", MapId = 78, PointId = 1 },
			new() { Name = "Cavern of Earth B3 - Center Stairs", MapGroup = "map_30031", MapName = "Map_30031_3", MapId = 78, PointId = 2 },
			new() { Name = "Cavern of Earth B4 - Right Stairs", MapGroup = "map_30031", MapName = "Map_30031_4", MapId = 79, PointId = 1 },
			new() { Name = "Cavern of Earth B4 - Left Stairs", MapGroup = "map_30031", MapName = "Map_30031_4", MapId = 79, PointId = 2 },
			new() { Name = "Cavern of Earth B5 - Bottom Stairs", MapGroup = "map_30031", MapName = "Map_30031_5", MapId = 80, PointId = 1 },
			new() { Name = "Giant's Cavern - West Entrance", MapGroup = "map_30041", MapName = "Map_30041_1", MapId = 81, PointId = 1 },
			new() { Name = "Giant's Cavern - East Entrance", MapGroup = "map_30041", MapName = "Map_30041_1", MapId = 81, PointId = 2 },
			new() { Name = "Mount Gulg B1 - Right Stairs", MapGroup = "map_30051", MapName = "Map_30051_1", MapId = 82, PointId = 1 },
			new() { Name = "Mount Gulg B1 - Left Stairs", MapGroup = "map_30051", MapName = "Map_30051_1", MapId = 82, PointId = 2 },
			new() { Name = "Mount Gulg B2 - Right Stairs", MapGroup = "map_30051", MapName = "Map_30051_2", MapId = 83, PointId = 1 },
			new() { Name = "Mount Gulg B2 - Left Stairs", MapGroup = "map_30051", MapName = "Map_30051_2", MapId = 83, PointId = 2 },
			new() { Name = "Mount Gulg B3 (Corridor) - Middle Stairs", MapGroup = "map_30051", MapName = "Map_30051_3", MapId = 84, PointId = 1 },
			new() { Name = "Mount Gulg B3 (Corridor) - Right Stairs", MapGroup = "map_30051", MapName = "Map_30051_3", MapId = 84, PointId = 2 },
			new() { Name = "Mount Gulg B3 (Maze) - Top Stairs", MapGroup = "map_30051", MapName = "Map_30051_4", MapId = 85, PointId = 1 },
			new() { Name = "Mount Gulg B3 (Maze) - Bottom Stairs", MapGroup = "map_30051", MapName = "Map_30051_4", MapId = 85, PointId = 2 },
			new() { Name = "Mount Gulg B4 (Squares) - Top Stairs", MapGroup = "map_30051", MapName = "Map_30051_5", MapId = 86, PointId = 1 },
			new() { Name = "Mount Gulg B4 (Squares) - Bottom Stairs", MapGroup = "map_30051", MapName = "Map_30051_5", MapId = 86, PointId = 2 },
			new() { Name = "Mount Gulg B4 (Agama) - Top Stairs", MapGroup = "map_30051", MapName = "Map_30051_5", MapId = 86, PointId = 3 },
			new() { Name = "Mount Gulg B4 (Agama) - Bottom Stairs", MapGroup = "map_30051", MapName = "Map_30051_5", MapId = 86, PointId = 4 },
			new() { Name = "Mount Gulg B5 - Center Stairs", MapGroup = "map_30051", MapName = "Map_30051_6", MapId = 87, PointId = 1 },
			new() { Name = "Cavern of Ice B1 (Entrance) - Top Stairs", MapGroup = "map_30061", MapName = "Map_30061_1", MapId = 88, PointId = 1 },
			new() { Name = "Cavern of Ice B1 (Entrance) - Bottom Stairs", MapGroup = "map_30061", MapName = "Map_30061_1", MapId = 88, PointId = 2 },
			new() { Name = "Cavern of Ice B1 (Backdoor) - Left Stairs", MapGroup = "map_30061", MapName = "Map_30061_1", MapId = 88, PointId = 3 },
			new() { Name = "Cavern of Ice B1 (Backdoor) - Hole", MapGroup = "map_30061", MapName = "Map_30061_1", MapId = 999, PointId = 0 }, // dummy point
			new() { Name = "Cavern of Ice B2 (Square) - Top Stairs", MapGroup = "map_30061", MapName = "Map_30061_2", MapId = 89, PointId = 1 },
			new() { Name = "Cavern of Ice B2 (Square) - Bottom Stairs", MapGroup = "map_30061", MapName = "Map_30061_2", MapId = 89, PointId = 2 },
			new() { Name = "Cavern of Ice B3 (Small) - Top Stairs", MapGroup = "map_30061", MapName = "Map_30061_3", MapId = 90, PointId = 1 },
			new() { Name = "Cavern of Ice B3 (Small) - Bottom Stairs", MapGroup = "map_30061", MapName = "Map_30061_3", MapId = 90, PointId = 2 },
			new() { Name = "Cavern of Ice B2 (Room) - Entrance", MapGroup = "map_30061", MapName = "Map_30061_4", MapId = 91, PointId = 1 },
			new() { Name = "Cavern of Ice B2 (Room) - Hole", MapGroup = "", MapName = "", MapId = 999, PointId = 1 }, // dummy point
			new() { Name = "Cavern of Ice B2 (Room) - Ledge", MapGroup = "", MapName = "", MapId = 91, PointId = 2 },
			new() { Name = "Cavern of Ice B3 (Treasury) - Right Stairs", MapGroup = "map_30061", MapName = "Map_30061_5", MapId = 92, PointId = 1 },
			new() { Name = "Cavern of Ice B3 (Treasury) - Trap Room", MapGroup = "", MapName = "", MapId = 92, PointId = 99 },
			new() { Name = "Citadel of Trials 1F - Entrance", MapGroup = "map_30071", MapName = "Map_30071_1", MapId = 93, PointId = 1 },
			new() { Name = "Citadel of Trials 1F - Throne", MapGroup = "map_30071", MapName = "Map_30071_1", MapId = 93, PointId = 2 },
			new() { Name = "Citadel of Trials 2F - Maze", MapGroup = "map_30071", MapName = "Map_30071_2", MapId = 94, PointId = 1 },

			new() { Name = "Trials Maze - Center North-East I", MapGroup = "map_30071", MapName = "Map_30071_2", MapId = 94, PointId = 3 },
			new() { Name = "Trials Maze - Center North-East II", MapGroup = "map_30071", MapName = "Map_30071_2", MapId = 94, PointId = 302 },
			new() { Name = "Trials Maze - Center North-East III", MapGroup = "map_30071", MapName = "Map_30071_2", MapId = 94, PointId = 303 },
			new() { Name = "Trials Maze - Center Split I", MapGroup = "map_30071", MapName = "Map_30071_2", MapId = 94, PointId = 4 },
			new() { Name = "Trials Maze - Center Split II", MapGroup = "map_30071", MapName = "Map_30071_2", MapId = 94, PointId = 12 },
			new() { Name = "Trials Maze - Center South-West I", MapGroup = "map_30071", MapName = "Map_30071_2", MapId = 94, PointId = 5 },
			new() { Name = "Trials Maze - Center South-West II", MapGroup = "map_30071", MapName = "Map_30071_2", MapId = 94, PointId = 300 },
			new() { Name = "Trials Maze - Center South-East", MapGroup = "map_30071", MapName = "Map_30071_2", MapId = 94, PointId = 6 },
			new() { Name = "Trials Maze - Lower Corner Split I", MapGroup = "map_30071", MapName = "Map_30071_2", MapId = 94, PointId = 7 },
			new() { Name = "Trials Maze - Lower Corner Split II", MapGroup = "map_30071", MapName = "Map_30071_2", MapId = 94, PointId = 301 },
			new() { Name = "Trials Maze - Side vertical", MapGroup = "map_30071", MapName = "Map_30071_2", MapId = 94, PointId = 8 },
			new() { Name = "Trials Maze - Upper Corner Split", MapGroup = "map_30071", MapName = "Map_30071_2", MapId = 94, PointId = 10 },
			new() { Name = "Trials Maze - Four Pillars", MapGroup = "map_30071", MapName = "Map_30071_2", MapId = 94, PointId = 11 },
			new() { Name = "Trials Maze - Lower Horizontal", MapGroup = "map_30071", MapName = "Map_30071_2", MapId = 94, PointId = 304 },
			new() { Name = "Trials Maze - Corner Exit", MapGroup = "map_30071", MapName = "Map_30071_2", MapId = 94, PointId = 13 },

			new() { Name = "Sunken Shrine 1F - Bottom Stairs", MapGroup = "map_30081", MapName = "Map_30081_1", MapId = 96, PointId = 1 },
			new() { Name = "Sunken Shrine 2F (Sunken City) - Bottom Stairs", MapGroup = "map_30081", MapName = "Map_30081_2", MapId = 97, PointId = 1 },
			new() { Name = "Sunken Shrine 2F (Sunken City) - Top Stairs", MapGroup = "map_30081", MapName = "Map_30081_2", MapId = 97, PointId = 2 },
			new() { Name = "Sunken Shrine 2F (Sharknado) - Right Stairs", MapGroup = "map_30081", MapName = "Map_30081_2", MapId = 97, PointId = 3 },
			new() { Name = "Sunken Shrine 2F (Sharknado) - Left Stairs", MapGroup = "map_30081", MapName = "Map_30081_2", MapId = 97, PointId = 4 },
			new() { Name = "Sunken Shrine 3F (Split) - Left Stairs", MapGroup = "map_30081", MapName = "Map_30081_3", MapId = 98, PointId = 1 },
			new() { Name = "Sunken Shrine 3F (Split) - Right Stairs", MapGroup = "map_30081", MapName = "Map_30081_3", MapId = 98, PointId = 2 },
			new() { Name = "Sunken Shrine 3F (Split) - Bottom Stairs", MapGroup = "map_30081", MapName = "Map_30081_3", MapId = 98, PointId = 101 },
			new() { Name = "Sunken Shrine 3F (Small) - Bottom Stairs", MapGroup = "map_30081", MapName = "Map_30081_4", MapId = 99, PointId = 1 },
			new() { Name = "Sunken Shrine 3F (Small) - Top Stairs", MapGroup = "map_30081", MapName = "Map_30081_4", MapId = 99, PointId = 2 },
			new() { Name = "Sunken Shrine 3F (Vertical) - Top Stairs", MapGroup = "map_30081", MapName = "Map_30081_5", MapId = 100, PointId = 1 },
			new() { Name = "Sunken Shrine 3F (Vertical) - Bottom Stairs", MapGroup = "map_30081", MapName = "Map_30081_5", MapId = 100, PointId = 2 },
			new() { Name = "Sunken Shrine 4F (TFC) - Top Stairs", MapGroup = "map_30081", MapName = "Map_30081_6", MapId = 101, PointId = 1 },
			new() { Name = "Sunken Shrine 4F (TFC) - Bottom Stairs", MapGroup = "map_30081", MapName = "Map_30081_6", MapId = 101, PointId = 2 },
			new() { Name = "Sunken Shrine 4F (Square) - Top Stairs", MapGroup = "map_30081", MapName = "Map_30081_7", MapId = 102, PointId = 1 },
			new() { Name = "Sunken Shrine 4F (Square) - Bottom Stairs", MapGroup = "map_30081", MapName = "Map_30081_7", MapId = 102, PointId = 2 },
			new() { Name = "Sunken Shrine 5F - Center Stairs", MapGroup = "map_30081", MapName = "Map_30081_8", MapId = 103, PointId = 1 },
			new() { Name = "Waterfall - Entrance", MapGroup = "map_30091", MapName = "Map_30091_1", MapId = 104, PointId = 1 },
			new() { Name = "Mirage Tower 1F - Right Stairs", MapGroup = "map_30101", MapName = "Map_30101_1", MapId = 105, PointId = 1 },
			new() { Name = "Mirage Tower 1F - Left Stairs", MapGroup = "map_30101", MapName = "Map_30101_1", MapId = 105, PointId = 2 },
			new() { Name = "Mirage Tower 2F - Bottom Stairs", MapGroup = "map_30101", MapName = "Map_30101_2", MapId = 106, PointId = 1 },
			new() { Name = "Mirage Tower 2F - Top Stairs", MapGroup = "map_30101", MapName = "Map_30101_2", MapId = 106, PointId = 2 },
			new() { Name = "Mirage Tower 3F - Top Stairs", MapGroup = "map_30101", MapName = "Map_30101_3", MapId = 107, PointId = 1 },
			new() { Name = "Mirage Tower 3F - Center Warp", MapGroup = "map_30101", MapName = "Map_30101_3", MapId = 107, PointId = 2 },
			new() { Name = "Flying Fortress 1F - Center Warp", MapGroup = "map_30111", MapName = "Map_30111_1", MapId = 108, PointId = 1 },
			new() { Name = "Flying Fortress 1F - Top Warp", MapGroup = "map_30111", MapName = "Map_30111_1", MapId = 108, PointId = 2 },
			new() { Name = "Flying Fortress 2F - Top Warp", MapGroup = "map_30111", MapName = "Map_30111_2", MapId = 109, PointId = 1 },
			new() { Name = "Flying Fortress 2F - Bottom Warp", MapGroup = "map_30111", MapName = "Map_30111_2", MapId = 109, PointId = 2 },
			new() { Name = "Flying Fortress 3F - Center Warp", MapGroup = "map_30111", MapName = "Map_30111_3", MapId = 110, PointId = 1 },
			new() { Name = "Flying Fortress 3F - Left Warp", MapGroup = "map_30111", MapName = "Map_30111_3", MapId = 110, PointId = 2 },
			new() { Name = "Flying Fortress 4F - Entrance Warp", MapGroup = "map_30111", MapName = "Map_30111_4", MapId = 111, PointId = 1 },
			new() { Name = "Flying Fortress 4F - Exit Warp", MapGroup = "map_30111", MapName = "Map_30111_4", MapId = 111, PointId = 2 },
			new() { Name = "Flying Fortress 5F - Bottom Warp", MapGroup = "map_30111", MapName = "Map_30111_5", MapId = 112, PointId = 1 },
			new() { Name = "Chaos Shrine 1F - Center Warp", MapGroup = "map_30121", MapName = "Map_30121_1", MapId = 113, PointId = 1 },
			new() { Name = "Chaos Shrine 1F (Entrance) - Right Stairs", MapGroup = "map_30121", MapName = "Map_30121_1", MapId = 113, PointId = 2 },
			new() { Name = "Chaos Shrine 1F (Entrance) - Left Stairs", MapGroup = "map_30121", MapName = "Map_30121_1", MapId = 113, PointId = 3 },
			new() { Name = "Chaos Shrine 1F (Corridor) - Right Stairs", MapGroup = "map_30121", MapName = "Map_30121_1", MapId = 113, PointId = 4 },
			new() { Name = "Chaos Shrine 1F (Corridor) - Left Stairs", MapGroup = "map_30121", MapName = "Map_30121_1", MapId = 113, PointId = 5 },
			new() { Name = "Chaos Shrine 2F (Corridor) - Left Stairs", MapGroup = "map_30121", MapName = "Map_30121_2", MapId = 114, PointId = 1 },
			new() { Name = "Chaos Shrine 2F (Corridor) - Right Stairs", MapGroup = "map_30121", MapName = "Map_30121_2", MapId = 114, PointId = 2 },
			new() { Name = "Chaos Shrine 2F (Plaza) - Center Stairs", MapGroup = "map_30121", MapName = "Map_30121_2", MapId = 114, PointId = 3 },
			new() { Name = "Chaos Shrine 2F (Plaza) - Left Stairs", MapGroup = "map_30121", MapName = "Map_30121_2", MapId = 114, PointId = 4 },
			new() { Name = "Chaos Shrine 3F (Plaza) - Left Stairs", MapGroup = "map_30121", MapName = "Map_30121_3", MapId = 115, PointId = 1 },
			new() { Name = "Chaos Shrine 3F (Plaza) - Center Stairs", MapGroup = "map_30121", MapName = "Map_30121_3", MapId = 115, PointId = 2 },
			new() { Name = "Chaos Shrine B1 (Earth) - Left Stairs", MapGroup = "map_30121", MapName = "Map_30121_4", MapId = 116, PointId = 1 },
			new() { Name = "Chaos Shrine B1 (Deadend) - Dead End Stairs", MapGroup = "map_30121", MapName = "Map_30121_4", MapId = 116, PointId = 2 },
			new() { Name = "Chaos Shrine B1 (Earth) - Right Stairs", MapGroup = "map_30121", MapName = "Map_30121_4", MapId = 116, PointId = 3 },
			new() { Name = "Chaos Shrine B2 - Left Stairs", MapGroup = "map_30121", MapName = "Map_30121_5", MapId = 117, PointId = 1 },
			new() { Name = "Chaos Shrine B2 - Right Stairs", MapGroup = "map_30121", MapName = "Map_30121_5", MapId = 117, PointId = 2 },
			new() { Name = "Chaos Shrine B3 - Top Stairs", MapGroup = "map_30121", MapName = "Map_30121_6", MapId = 118, PointId = 1 },
			new() { Name = "Chaos Shrine B3 - Bottom Stairs", MapGroup = "map_30121", MapName = "Map_30121_6", MapId = 118, PointId = 2 },
			new() { Name = "Chaos Shrine B4 - Left Stairs", MapGroup = "map_30121", MapName = "Map_30121_7", MapId = 119, PointId = 1 },
			new() { Name = "Chaos Shrine B4 - Right Stairs", MapGroup = "map_30121", MapName = "Map_30121_7", MapId = 119, PointId = 2 },
			new() { Name = "Chaos Shrine B5 - Top Stairs", MapGroup = "map_30121", MapName = "Map_30121_8", MapId = 120, PointId = 1 },
		};

		public static Dictionary<string, string> TeleporterPairingsA = new()
		{
			{ "Overworld - Castle Cornelia", "Castle Cornelia 1F - Entrance" },
			{ "Overworld - Cornelia", "Cornelia - Entrance" },
			{ "Overworld - Chaos Shrine", "Chaos Shrine - Entrance" },
			{ "Overworld - Matoya's Cave", "Matoya's Cave - Entrance" },
			{ "Overworld - Pravoka", "Pravoka - Entrance" },
			{ "Overworld - Mount Duergar", "Mount Duergar - Entrance" },
			{ "Overworld - Elfheim", "Elfheim - Entrance" },
			{ "Overworld - Elven Castle", "Elven Castle - Entrance" },
			{ "Overworld - Western Keep", "Western Keep - Entrance" },
			{ "Overworld - Marsh Cave", "Marsh Cave B1 - Entrance" },
			{ "Overworld - Melmond", "Melmond - Entrance" },
			{ "Overworld - Cavern of Earth", "Cavern of Earth B1 - Center Stairs" },
			{ "Overworld - Giant's Cavern West", "Giant's Cavern - West Entrance" },
			{ "Overworld - Giant's Cavern East", "Giant's Cavern - East Entrance" },
			{ "Overworld - Sage's Cave", "Sage's Cave - Entrance" },
			{ "Overworld - Crescent Lake", "Crescent Lake - Entrance" },
			{ "Overworld - Mount Gulg", "Mount Gulg B1 - Right Stairs" },
			{ "Overworld - Cavern of Ice", "Cavern of Ice B1 (Entrance) - Top Stairs" },
			{ "Overworld - Dragon Caves (Plains)", "Dragon Caves (Plains) - Entrance" },
			{ "Overworld - Dragon Caves (Top)", "Dragon Caves (Top) - Entrance" },
			{ "Overworld - Dragon Caves (Marsh)", "Dragon Caves (Marsh) - Entrance" },
			{ "Overworld - Dragon Caves (Small)", "Dragon Caves (Small) - Entrance" },
			{ "Overworld - Dragon Caves (Forest)", "Dragon Caves (Forest) - Entrance" },
			{ "Overworld - Dragon Caves (Bahamut)", "Dragon Caves (Bahamut) - Entrance" },
			{ "Overworld - Citadel of Trials", "Citadel of Trials 1F - Entrance" },
			{ "Overworld - Onrac", "Onrac - Entrance" },
			{ "Overworld - Caravan", "Caravan - Entrance" },
			{ "Overworld - Gaia", "Gaia - Entrance" },
			{ "Overworld - Waterfall", "Waterfall - Entrance" },
			{ "Overworld - Lufenia", "Lufenia - Entrance" },
			{ "Overworld - Mirage Tower", "Mirage Tower 1F - Right Stairs" },
			{ "Castle Cornelia 1F - Stairs", "Castle Cornelia 2F - Stairs" },
			{ "Dragon Caves (Bahamut) - Bottom Stairs", "Dragon Caves (Bahamut) - Bahamut Hall" },
			{ "Onrac - Submarine Dock", "Sunken Shrine 3F (Split) - Bottom Stairs" },
			{ "Caravan - Outside Tent", "Caravan - Inside Tent" },
			{ "Chaos Shrine - Black Orb Warp", "Chaos Shrine 1F - Center Warp" },
			{ "Marsh Cave B1 - Top Stairs", "Marsh Cave B2 - Entrance" },
			{ "Marsh Cave B1 - Bottom Stairs", "Marsh Cave B2 - Upper Stairs" },
			{ "Marsh Cave B2 - Lower Stairs", "Marsh Cave B3 - Entrance" },
			{ "Cavern of Earth B1 - Right Stairs", "Cavern of Earth B2 - Left Stairs" },
			{ "Cavern of Earth B2 - Right Stairs", "Cavern of Earth B3 - Bottom Stairs" },
			{ "Cavern of Earth B3 - Center Stairs", "Cavern of Earth B4 - Right Stairs" },
			{ "Cavern of Earth B4 - Left Stairs", "Cavern of Earth B5 - Bottom Stairs" },
			{ "Mount Gulg B1 - Left Stairs", "Mount Gulg B2 - Right Stairs" },
			{ "Mount Gulg B2 - Left Stairs", "Mount Gulg B3 (Corridor) - Middle Stairs" },
			{ "Mount Gulg B3 (Corridor) - Right Stairs", "Mount Gulg B4 (Squares) - Top Stairs" },
			{ "Mount Gulg B4 (Squares) - Bottom Stairs", "Mount Gulg B3 (Maze) - Top Stairs" },
			{ "Mount Gulg B3 (Maze) - Bottom Stairs", "Mount Gulg B4 (Agama) - Top Stairs" },
			{ "Mount Gulg B4 (Agama) - Bottom Stairs", "Mount Gulg B5 - Center Stairs" },
			{ "Cavern of Ice B1 (Entrance) - Bottom Stairs", "Cavern of Ice B2 (Square) - Top Stairs" },
			{ "Cavern of Ice B2 (Square) - Bottom Stairs", "Cavern of Ice B3 (Small) - Top Stairs" },
			{ "Cavern of Ice B3 (Small) - Bottom Stairs", "Cavern of Ice B2 (Room) - Entrance" },
			{ "Cavern of Ice B3 (Treasury) - Right Stairs", "Cavern of Ice B1 (Backdoor) - Left Stairs" },
			{ "Citadel of Trials 1F - Throne", "Citadel of Trials 2F - Maze" },
			{ "Sunken Shrine 1F - Bottom Stairs", "Sunken Shrine 2F (Sharknado) - Left Stairs" },
			{ "Sunken Shrine 2F (Sharknado) - Right Stairs", "Sunken Shrine 3F (Vertical) - Bottom Stairs" },
			{ "Sunken Shrine 3F (Vertical) - Top Stairs", "Sunken Shrine 4F (Square) - Bottom Stairs" },
			{ "Sunken Shrine 4F (Square) - Top Stairs", "Sunken Shrine 3F (Small) - Top Stairs" },
			{ "Sunken Shrine 3F (Small) - Bottom Stairs", "Sunken Shrine 2F (Sunken City) - Top Stairs" },
			{ "Sunken Shrine 2F (Sunken City) - Bottom Stairs", "Sunken Shrine 3F (Split) - Left Stairs" },
			{ "Sunken Shrine 3F (Split) - Right Stairs", "Sunken Shrine 4F (TFC) - Top Stairs" },
			{ "Sunken Shrine 4F (TFC) - Bottom Stairs", "Sunken Shrine 5F - Center Stairs" },
			{ "Mirage Tower 1F - Left Stairs", "Mirage Tower 2F - Bottom Stairs" },
			{ "Mirage Tower 2F - Top Stairs", "Mirage Tower 3F - Top Stairs" },
			{ "Mirage Tower 3F - Center Warp", "Flying Fortress 1F - Center Warp" },
			{ "Flying Fortress 1F - Top Warp", "Flying Fortress 2F - Top Warp" },
			{ "Flying Fortress 2F - Bottom Warp", "Flying Fortress 3F - Center Warp" },
			{ "Flying Fortress 3F - Left Warp", "Flying Fortress 4F - Entrance Warp" },
			{ "Flying Fortress 4F - Exit Warp", "Flying Fortress 5F - Bottom Warp" },
			{ "Chaos Shrine 1F (Entrance) - Right Stairs", "Chaos Shrine 2F (Corridor) - Left Stairs" },
			{ "Chaos Shrine 1F (Entrance) - Left Stairs", "Chaos Shrine B1 (Deadend) - Dead End Stairs" },
			{ "Chaos Shrine 1F (Corridor) - Right Stairs", "Chaos Shrine 2F (Plaza) - Left Stairs" },
			{ "Chaos Shrine 1F (Corridor) - Left Stairs", "Chaos Shrine B1 (Earth) - Left Stairs" },
			{ "Chaos Shrine 2F (Corridor) - Right Stairs", "Chaos Shrine 3F (Plaza) - Left Stairs" },
			{ "Chaos Shrine 3F (Plaza) - Center Stairs", "Chaos Shrine 2F (Plaza) - Center Stairs" },
			{ "Chaos Shrine B1 (Earth) - Right Stairs", "Chaos Shrine B2 - Left Stairs" },
			{ "Chaos Shrine B2 - Right Stairs", "Chaos Shrine B3 - Top Stairs" },
			{ "Chaos Shrine B3 - Bottom Stairs", "Chaos Shrine B4 - Left Stairs" },
			{ "Chaos Shrine B4 - Right Stairs", "Chaos Shrine B5 - Top Stairs" },
		};

		public static Dictionary<string, string> TeleporterPairs = TeleporterPairingsA.Concat(TeleporterPairingsA.ToDictionary(t => t.Value, t => t.Key)).ToDictionary(t => t.Key, t => t.Value);

		public static Dictionary<(int map, int point), Teleporter> PointToTeleporters = Teleporters.ToDictionary(t => (t.MapId, t.PointId), t => t);
		public static Dictionary<string, Teleporter> NameToTeleporters = Teleporters.ToDictionary(t => t.Name, t => t);
	}
}
